/**
 * Member List Mock Data
 * Realistic test data for the Members List page
 */

import { MemberUser } from './member-list-type';

export const MEMBERS: MemberUser[] = [
  {
    id: 1,
    firstName: 'Sarah',
    lastName: 'Parker',
    email: 'sarah.parker@shyft.com',
    profileImage: 'assets/images/user/avatar-1.jpg',
    role: 'Rider',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Official Rider',
    membershipNumber: 'SAEF-2024-001',
    dateJoined: new Date('2024-01-15'),
    isActive: true,
    isBanned: false
  },
  {
    id: 2,
    firstName: 'Alex',
    lastName: 'Johnson',
    email: 'alex.johnson@byteorbit.com',
    profileImage: 'assets/images/user/avatar-2.jpg',
    role: 'Show Holding Body',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'SHB Member',
    membershipNumber: 'SAEF-2024-002',
    dateJoined: new Date('2024-02-10'),
    isActive: true,
    isBanned: false
  },
  {
    id: 3,
    firstName: 'Emma',
    lastName: 'Williams',
    email: 'emma.williams@shyft.com',
    profileImage: 'assets/images/user/avatar-3.jpg',
    role: 'Judge',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Official Judge',
    membershipNumber: 'SAEF-2024-003',
    dateJoined: new Date('2023-11-20'),
    isActive: true,
    isBanned: false
  },
  {
    id: 4,
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@byteorbit.com',
    profileImage: 'assets/images/user/avatar-4.jpg',
    role: 'Rider',
    status: 'Inactive',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Recreational Rider',
    membershipNumber: 'SAEF-2023-045',
    dateJoined: new Date('2023-08-05'),
    isActive: false,
    isBanned: false
  },
  {
    id: 5,
    firstName: 'Jessica',
    lastName: 'Davis',
    email: 'jessica.davis@shyft.com',
    profileImage: 'assets/images/user/avatar-5.jpg',
    role: 'Club',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Club Member',
    membershipNumber: 'SAEF-2024-004',
    dateJoined: new Date('2024-03-01'),
    isActive: true,
    isBanned: false
  },
  {
    id: 6,
    firstName: 'David',
    lastName: 'Martinez',
    email: 'david.martinez@byteorbit.com',
    profileImage: 'assets/images/user/avatar-1.jpg',
    role: 'Admin',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Administrator',
    membershipNumber: 'SAEF-ADMIN-001',
    dateJoined: new Date('2023-01-10'),
    isActive: true,
    isBanned: false
  },
  {
    id: 7,
    firstName: 'Olivia',
    lastName: 'Garcia',
    email: 'olivia.garcia@shyft.com',
    profileImage: 'assets/images/user/avatar-2.jpg',
    role: 'Rider',
    status: 'Banned',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Official Rider',
    membershipNumber: 'SAEF-2023-078',
    dateJoined: new Date('2023-06-15'),
    isActive: false,
    isBanned: true
  },
  {
    id: 8,
    firstName: 'James',
    lastName: 'Rodriguez',
    email: 'james.rodriguez@byteorbit.com',
    profileImage: 'assets/images/user/avatar-3.jpg',
    role: 'Official',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'SAEF Official',
    membershipNumber: 'SAEF-2024-005',
    dateJoined: new Date('2024-01-20'),
    isActive: true,
    isBanned: false
  },
  {
    id: 9,
    firstName: 'Sophia',
    lastName: 'Anderson',
    email: 'sophia.anderson@shyft.com',
    profileImage: 'assets/images/user/avatar-4.jpg',
    role: 'Rider',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Official Rider',
    membershipNumber: 'SAEF-2024-006',
    dateJoined: new Date('2024-02-28'),
    isActive: true,
    isBanned: false
  },
  {
    id: 10,
    firstName: 'Daniel',
    lastName: 'Wilson',
    email: 'daniel.wilson@byteorbit.com',
    profileImage: 'assets/images/user/avatar-5.jpg',
    role: 'Rider',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Recreational Rider',
    membershipNumber: 'SAEF-2024-007',
    dateJoined: new Date('2024-03-10'),
    isActive: true,
    isBanned: false
  },
  {
    id: 11,
    firstName: 'Isabella',
    lastName: 'Taylor',
    email: 'isabella.taylor@shyft.com',
    profileImage: 'assets/images/user/avatar-1.jpg',
    role: 'Judge',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Official Judge',
    membershipNumber: 'SAEF-2023-089',
    dateJoined: new Date('2023-09-12'),
    isActive: true,
    isBanned: false
  },
  {
    id: 12,
    firstName: 'Matthew',
    lastName: 'Thomas',
    email: 'matthew.thomas@byteorbit.com',
    profileImage: 'assets/images/user/avatar-2.jpg',
    role: 'Show Holding Body',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'SHB Member',
    membershipNumber: 'SAEF-2024-008',
    dateJoined: new Date('2024-01-05'),
    isActive: true,
    isBanned: false
  },
  {
    id: 13,
    firstName: 'Charlotte',
    lastName: 'Moore',
    email: 'charlotte.moore@shyft.com',
    profileImage: 'assets/images/user/avatar-3.jpg',
    role: 'Rider',
    status: 'Inactive',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Official Rider',
    membershipNumber: 'SAEF-2023-034',
    dateJoined: new Date('2023-05-18'),
    isActive: false,
    isBanned: false
  },
  {
    id: 14,
    firstName: 'Christopher',
    lastName: 'Jackson',
    email: 'christopher.jackson@byteorbit.com',
    profileImage: 'assets/images/user/avatar-4.jpg',
    role: 'SAEF Admin',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'SAEF Administrator',
    membershipNumber: 'SAEF-ADMIN-002',
    dateJoined: new Date('2023-02-14'),
    isActive: true,
    isBanned: false
  },
  {
    id: 15,
    firstName: 'Amelia',
    lastName: 'White',
    email: 'amelia.white@shyft.com',
    profileImage: 'assets/images/user/avatar-5.jpg',
    role: 'Rider',
    status: 'Active',
    country: 'South Africa',
    countryCode: 'ZA',
    membershipType: 'Recreational Rider',
    membershipNumber: 'SAEF-2024-009',
    dateJoined: new Date('2024-03-15'),
    isActive: true,
    isBanned: false
  }
];

