# Generated by Django 5.2 on 2026-04-02 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the year",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Name of the competition year (e.g., "2024 Season")',
                        max_length=200,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Year number (e.g., 2024)"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the competition year"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="End date of the competition year"),
                ),
                (
                    "is_registration_open",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether registration is currently open",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETE", "Complete"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Year status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this year"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Competition Year",
                "verbose_name_plural": "Competition Years",
                "db_table": "competition_years",
                "ordering": ["-year", "-start_date"],
                "indexes": [
                    models.Index(fields=["year"], name="competition_year_df24de_idx"),
                    models.Index(
                        fields=["status"], name="competition_status_1c0db8_idx"
                    ),
                    models.Index(
                        fields=["is_registration_open"],
                        name="competition_is_regi_2eb2d2_idx",
                    ),
                    models.Index(
                        fields=["-start_date"], name="competition_start_d_9771d9_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="end_date_gte_start_date",
                    )
                ],
            },
        ),
    ]
