# Generated by Django 5.2 on 2026-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Name of the competition year (e.g., "2024 Season")',
                        max_length=100,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Year number (e.g., 2024)"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the competition year"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="End date of the competition year"),
                ),
                (
                    "is_registration_open",
                    models.BooleanField(
                        default=False,
                        help_text="Whether registration is currently open for this year",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETE", "Complete"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="PENDING",
                        help_text="Current status of the competition year",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or information about this year",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the year was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the year was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Year",
                "verbose_name_plural": "Competition Years",
                "db_table": "years",
                "ordering": ["-year", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["year", "status"], name="years_year_f9349d_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="years_start_d_24039d_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="end_date_after_start_date",
                        violation_error_message="End date must be on or after start date",
                    )
                ],
            },
        ),
    ]
