/**
 * Horses List Mock Data
 * Realistic test data for the Horses List feature
 */

import { Horse } from './horses-list-type';

/**
 * Mock Horses Data
 * 15 realistic Horses with diverse breeds, colors, and statuses
 */
export const HORSES: Horse[] = [
  {
    id: 1,
    name: 'Midnight Star',
    microchipNumber: 'ZA953000012345678',
    passportNumber: 'FEI104AB12345',
    dateOfBirth: new Date('2015-04-12'),
    breed: 'Warmblood',
    color: 'Black',
    gender: 'Stallion',
    image: 'assets/images/horses/horse-1.jpg',
    status: 'Active',
    dateCreated: new Date('2020-03-15'),
    isActive: true,
    ownerName: 'Sarah Mitchell',
    ownerEmail: 'sarah.mitchell@dressage.co.za',
    height: 16.2,
    sire: 'Dark Knight',
    dam: 'Starlight Princess'
  },
  {
    id: 2,
    name: 'Golden Dream',
    microchipNumber: 'ZA953000023456789',
    passportNumber: 'FEI104AB23456',
    dateOfBirth: new Date('2016-06-20'),
    breed: 'Hanoverian',
    color: 'Chestnut',
    gender: 'Mare',
    image: 'assets/images/horses/horse-2.jpg',
    status: 'Active',
    dateCreated: new Date('2019-06-20'),
    isActive: true,
    ownerName: 'Michael Thompson',
    ownerEmail: 'michael.thompson@dressage.com',
    height: 16.0,
    sire: 'Golden Boy',
    dam: 'Dream Catcher'
  },
  {
    id: 3,
    name: 'Silver Shadow',
    microchipNumber: 'ZA953000034567890',
    passportNumber: 'FEI104AB34567',
    dateOfBirth: new Date('2014-08-15'),
    breed: 'Thoroughbred',
    color: 'Grey',
    gender: 'Gelding',
    image: 'assets/images/horses/horse-3.jpg',
    status: 'Active',
    dateCreated: new Date('2018-01-10'),
    isActive: true,
    ownerName: 'Jennifer Adams',
    ownerEmail: 'jennifer.adams@dressage.co.za',
    height: 16.3,
    sire: 'Silver Lining',
    dam: 'Shadow Dancer'
  },
  {
    id: 4,
    name: 'Royal Dancer',
    microchipNumber: 'ZA953000045678901',
    passportNumber: 'FEI104AB45678',
    dateOfBirth: new Date('2017-03-22'),
    breed: 'Dutch Warmblood',
    color: 'Bay',
    gender: 'Mare',
    image: 'assets/images/horses/horse-4.jpg',
    status: 'Active',
    dateCreated: new Date('2020-09-05'),
    isActive: true,
    ownerName: 'David Williams',
    ownerEmail: 'david.williams@dressage.com',
    height: 16.1,
    sire: 'Royal Prince',
    dam: 'Dancing Queen'
  },
  {
    id: 5,
    name: 'Crimson Fire',
    microchipNumber: 'ZA953000056789012',
    passportNumber: 'FEI104AB56789',
    dateOfBirth: new Date('2013-11-08'),
    breed: 'Andalusian',
    color: 'Chestnut',
    gender: 'Stallion',
    image: 'assets/images/horses/horse-5.jpg',
    status: 'Inactive',
    dateCreated: new Date('2017-07-22'),
    isActive: false,
    ownerName: 'Emma van der Merwe',
    ownerEmail: 'emma.vandermerwe@dressage.co.za',
    height: 15.3,
    sire: 'Crimson King',
    dam: 'Fire Dancer'
  },
  {
    id: 6,
    name: 'Ocean Breeze',
    microchipNumber: 'ZA953000067890123',
    passportNumber: 'FEI104AB67890',
    dateOfBirth: new Date('2018-05-14'),
    breed: 'Lusitano',
    color: 'Grey',
    gender: 'Mare',
    image: 'assets/images/horses/horse-1.jpg',
    status: 'Active',
    dateCreated: new Date('2021-11-18'),
    isActive: true,
    ownerName: 'Robert Johnson',
    ownerEmail: 'robert.johnson@dressage.com',
    height: 15.2,
    sire: 'Ocean Wave',
    dam: 'Breeze Dancer'
  },
  {
    id: 7,
    name: 'Thunder Storm',
    microchipNumber: 'ZA953000078901234',
    passportNumber: 'FEI104AB78901',
    dateOfBirth: new Date('2016-09-30'),
    breed: 'Oldenburg',
    color: 'Dark Bay',
    gender: 'Gelding',
    image: 'assets/images/horses/horse-2.jpg',
    status: 'Active',
    dateCreated: new Date('2019-04-12'),
    isActive: true,
    ownerName: 'Linda Botha',
    ownerEmail: 'linda.botha@dressage.co.za',
    height: 17.0,
    sire: 'Thunder Bolt',
    dam: 'Storm Cloud'
  },
  {
    id: 8,
    name: 'Moonlight Sonata',
    microchipNumber: 'ZA953000089012345',
    passportNumber: 'FEI104AB89012',
    dateOfBirth: new Date('2015-12-25'),
    breed: 'Trakehner',
    color: 'Black',
    gender: 'Mare',
    image: 'assets/images/horses/horse-3.jpg',
    status: 'Active',
    dateCreated: new Date('2018-10-08'),
    isActive: true,
    ownerName: 'James Peterson',
    ownerEmail: 'james.peterson@dressage.com',
    height: 16.2,
    sire: 'Moonlight Magic',
    dam: 'Sonata Star'
  },
  {
    id: 9,
    name: 'Diamond Dust',
    microchipNumber: 'ZA953000090123456',
    passportNumber: 'FEI104AB90123',
    dateOfBirth: new Date('2019-02-14'),
    breed: 'KWPN',
    color: 'Grey',
    gender: 'Gelding',
    image: 'assets/images/horses/horse-4.jpg',
    status: 'Active',
    dateCreated: new Date('2022-02-14'),
    isActive: true,
    ownerName: 'Sophie Kruger',
    ownerEmail: 'sophie.kruger@dressage.co.za',
    height: 16.1,
    sire: 'Diamond King',
    dam: 'Dusty Rose'
  },
  {
    id: 10,
    name: 'Phoenix Rising',
    microchipNumber: 'ZA953000001234567',
    passportNumber: 'FEI104AB01234',
    dateOfBirth: new Date('2014-07-19'),
    breed: 'Friesian',
    color: 'Black',
    gender: 'Stallion',
    image: 'assets/images/horses/horse-5.jpg',
    status: 'Inactive',
    dateCreated: new Date('2017-08-30'),
    isActive: false,
    ownerName: 'Thomas Maluleke',
    ownerEmail: 'thomas.maluleke@dressage.com',
    height: 16.0,
    sire: 'Phoenix Fire',
    dam: 'Rising Star'
  },
  {
    id: 11,
    name: 'Velvet Rose',
    microchipNumber: 'ZA953000011234568',
    passportNumber: 'FEI104AB11234',
    dateOfBirth: new Date('2017-10-05'),
    breed: 'Warmblood',
    color: 'Bay',
    gender: 'Mare',
    image: 'assets/images/horses/horse-1.jpg',
    status: 'Active',
    dateCreated: new Date('2020-06-25'),
    isActive: true,
    ownerName: 'Patricia Nkosi',
    ownerEmail: 'patricia.nkosi@dressage.co.za',
    height: 16.2,
    sire: 'Velvet Touch',
    dam: 'Rose Garden'
  },
  {
    id: 12,
    name: 'Copper Coin',
    microchipNumber: 'ZA953000021234569',
    passportNumber: 'FEI104AB21234',
    dateOfBirth: new Date('2016-01-28'),
    breed: 'Quarter Horse',
    color: 'Sorrel',
    gender: 'Gelding',
    image: 'assets/images/horses/horse-2.jpg',
    status: 'Active',
    dateCreated: new Date('2019-05-17'),
    isActive: true,
    ownerName: 'Andrew Smith',
    ownerEmail: 'andrew.smith@dressage.com',
    height: 15.1,
    sire: 'Copper King',
    dam: 'Golden Coin'
  }
];

