# Generated by Django 5.2 on 2026-04-02 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("years", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the membership type",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the membership type"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this membership type is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the membership"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="memberships_name_a3a064_idx"),
                    models.Index(
                        fields=["is_active"], name="memberships_is_acti_c31b58_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="memberships_created_0b9d06_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the subscription", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the subscription"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subscription fee amount",
                        max_digits=10,
                    ),
                ),
                (
                    "is_recreational",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a recreational (non-competitive) subscription",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this subscription is currently available",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the subscription"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        help_text="Associated membership type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="memberships.membership",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        help_text="Associated competition year",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="years.year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["membership", "year"],
                        name="memberships_members_f5d1f0_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="memberships_is_acti_937332_idx"
                    ),
                    models.Index(
                        fields=["is_recreational"],
                        name="memberships_is_recr_df1e8a_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="memberships_created_e21f35_idx"
                    ),
                ],
                "unique_together": {("membership", "year", "is_recreational")},
            },
        ),
    ]
