# Generated by Django 5.2 on 2026-04-02 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the user",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address (used as username for authentication)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MR", "Mr"),
                            ("MRS", "Mrs"),
                            ("MS", "Ms"),
                            ("MISS", "Miss"),
                            ("DR", "Dr"),
                            ("PROF", "Prof"),
                        ],
                        help_text="User title (Mr, Mrs, Ms, Dr, Prof, etc.)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="User first name", max_length=150),
                ),
                (
                    "maiden_name",
                    models.CharField(
                        blank=True,
                        help_text="User maiden name (optional)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(help_text="User last name", max_length=150),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("RIDER", "Rider"),
                            ("CLUB", "Club"),
                            ("PROVINCIAL", "Provincial"),
                            ("SAEF", "SAEF"),
                            ("SHOW_HOLDING_BODY", "Show Holding Body"),
                            ("ADMIN", "Administrator"),
                            ("OFFICIAL", "Official"),
                        ],
                        default="RIDER",
                        help_text="User role determining permissions and access level",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into the admin site",
                    ),
                ),
                (
                    "email_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user email was confirmed",
                        null=True,
                    ),
                ),
                (
                    "banned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user account was banned",
                        null=True,
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user account was activated",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the user was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the user was last updated",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(fields=["role"], name="users_role_0ace22_idx"),
                    models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
                ],
            },
        ),
    ]
