# Generated by Django 5.2 on 2026-04-01 13:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_verified_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when the user was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="email_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the user email was confirmed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="maiden_name",
            field=models.CharField(
                blank=True,
                help_text="User maiden name (optional)",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MR", "Mr"),
                    ("MRS", "Mrs"),
                    ("MS", "Ms"),
                    ("MISS", "Miss"),
                    ("DR", "Dr"),
                    ("PROF", "Prof"),
                ],
                help_text="User title (Mr, Mrs, Ms, Dr, Prof, etc.)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the user was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email address (used as username for authentication)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(help_text="User first name", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the user",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into the admin site",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(help_text="User last name", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("RIDER", "Rider"),
                    ("CLUB", "Club"),
                    ("PROVINCIAL", "Provincial"),
                    ("SAEF", "SAEF"),
                    ("SHOW_HOLDING_BODY", "Show Holding Body"),
                    ("ADMIN", "Administrator"),
                    ("OFFICIAL", "Official"),
                ],
                default="RIDER",
                help_text="User role determining permissions and access level",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
    ]
