/**
 * Shows List Mock Data
 * Realistic test data for the Shows (Competitions) List feature
 */

import { Show } from './shows-list-type';

/**
 * Mock Shows Data
 * 15 realistic Shows with diverse levels and statuses
 */
export const SHOWS: Show[] = [
  {
    id: 1,
    name: 'Cape Town Spring Dressage Championship',
    showHoldingBody: 'Western Cape Dressage Association',
    showHoldingBodyId: 1,
    venue: 'Cape Town Equestrian Centre',
    startDate: new Date('2024-09-15'),
    endDate: new Date('2024-09-17'),
    entryClosingDate: new Date('2024-09-01'),
    status: 'Upcoming',
    level: 'All Levels',
    dateCreated: new Date('2024-01-15'),
    isActive: true,
    description: 'Annual spring championship featuring all levels of dressage competition',
    maxEntries: 150,
    currentEntries: 87,
    entryFee: 450.00,
    contactEmail: 'entries@wcdressage.co.za',
    contactPhone: '+27 21 794 3000',
    province: 'Western Cape',
    city: 'Cape Town',
    judges: ['Sarah Mitchell', 'Jennifer Adams'],
    classes: ['Preliminary 1A', 'Novice 2B', 'Elementary 3C', 'Medium 4A', 'Advanced 5B']
  },
  {
    id: 2,
    name: 'Johannesburg Grand Prix Qualifier',
    showHoldingBody: 'Gauteng Equestrian Federation',
    showHoldingBodyId: 2,
    venue: 'Johannesburg Show Grounds',
    startDate: new Date('2024-08-20'),
    endDate: new Date('2024-08-22'),
    entryClosingDate: new Date('2024-08-05'),
    status: 'Open',
    level: 'Grand Prix',
    dateCreated: new Date('2024-02-10'),
    isActive: true,
    description: 'Elite Grand Prix competition and national team qualifier',
    maxEntries: 80,
    currentEntries: 62,
    entryFee: 850.00,
    contactEmail: 'info@gautengequestrian.com',
    contactPhone: '+27 11 883 5000',
    province: 'Gauteng',
    city: 'Johannesburg',
    judges: ['Michael Thompson', 'Sophie Kruger'],
    classes: ['Grand Prix', 'Grand Prix Special', 'Grand Prix Freestyle']
  },
  {
    id: 3,
    name: 'KZN Coastal Dressage Festival',
    showHoldingBody: 'KwaZulu-Natal Dressage Society',
    showHoldingBodyId: 3,
    venue: 'Durban Equestrian Park',
    startDate: new Date('2024-10-05'),
    endDate: new Date('2024-10-07'),
    entryClosingDate: new Date('2024-09-20'),
    status: 'Upcoming',
    level: 'All Levels',
    dateCreated: new Date('2024-03-05'),
    isActive: true,
    description: 'Coastal festival celebrating dressage with competitions for all levels',
    maxEntries: 120,
    currentEntries: 45,
    entryFee: 400.00,
    contactEmail: 'coastal@kzndressage.co.za',
    contactPhone: '+27 31 561 4000',
    province: 'KwaZulu-Natal',
    city: 'Durban',
    judges: ['Jennifer Adams', 'James Peterson'],
    classes: ['Preliminary 1B', 'Novice 2A', 'Elementary 3A', 'Medium 4B']
  },
  {
    id: 4,
    name: 'Pretoria Winter Series - Round 1',
    showHoldingBody: 'Gauteng Equestrian Federation',
    showHoldingBodyId: 2,
    venue: 'Pretoria Equestrian Centre',
    startDate: new Date('2024-06-15'),
    endDate: new Date('2024-06-16'),
    entryClosingDate: new Date('2024-06-01'),
    status: 'Completed',
    level: 'Preliminary',
    dateCreated: new Date('2024-01-20'),
    isActive: false,
    description: 'First round of the popular winter series for preliminary riders',
    maxEntries: 100,
    currentEntries: 100,
    entryFee: 350.00,
    contactEmail: 'winter@gautengequestrian.com',
    contactPhone: '+27 12 346 8000',
    province: 'Gauteng',
    city: 'Pretoria',
    judges: ['David Williams', 'Linda Botha'],
    classes: ['Preliminary 1A', 'Preliminary 1B', 'Preliminary 1C']
  },
  {
    id: 5,
    name: 'Stellenbosch Autumn Classic',
    showHoldingBody: 'Western Cape Dressage Association',
    showHoldingBodyId: 1,
    venue: 'Stellenbosch Equestrian Estate',
    startDate: new Date('2024-04-12'),
    endDate: new Date('2024-04-14'),
    entryClosingDate: new Date('2024-03-28'),
    status: 'Completed',
    level: 'Medium',
    dateCreated: new Date('2023-12-10'),
    isActive: false,
    description: 'Prestigious medium level competition in the heart of wine country',
    maxEntries: 90,
    currentEntries: 88,
    entryFee: 550.00,
    contactEmail: 'autumn@wcdressage.co.za',
    contactPhone: '+27 21 887 2000',
    province: 'Western Cape',
    city: 'Stellenbosch',
    judges: ['Sarah Mitchell', 'Emma van der Merwe'],
    classes: ['Medium 4A', 'Medium 4B', 'Medium 4C']
  },
  {
    id: 6,
    name: 'Port Elizabeth Novice Championship',
    showHoldingBody: 'Eastern Cape Equestrian Association',
    showHoldingBodyId: 4,
    venue: 'Gqeberha Show Grounds',
    startDate: new Date('2024-11-08'),
    endDate: new Date('2024-11-10'),
    entryClosingDate: new Date('2024-10-25'),
    status: 'Upcoming',
    level: 'Novice',
    dateCreated: new Date('2024-04-15'),
    isActive: true,
    description: 'Regional championship for novice level riders',
    maxEntries: 110,
    currentEntries: 38,
    entryFee: 380.00,
    contactEmail: 'novice@ecdressage.co.za',
    contactPhone: '+27 41 583 3000',
    province: 'Eastern Cape',
    city: 'Gqeberha',
    judges: ['Robert Johnson', 'Patricia Nkosi'],
    classes: ['Novice 2A', 'Novice 2B', 'Novice 2C']
  },
  {
    id: 7,
    name: 'Bloemfontein Elementary Open',
    showHoldingBody: 'Free State Dressage Club',
    showHoldingBodyId: 5,
    venue: 'Bloemfontein Equestrian Park',
    startDate: new Date('2024-08-10'),
    endDate: new Date('2024-08-11'),
    entryClosingDate: new Date('2024-07-27'),
    status: 'Open',
    level: 'Elementary',
    dateCreated: new Date('2024-03-20'),
    isActive: true,
    description: 'Open competition for elementary level combinations',
    maxEntries: 85,
    currentEntries: 56,
    entryFee: 420.00,
    contactEmail: 'elementary@fsdressage.co.za',
    contactPhone: '+27 51 447 9000',
    province: 'Free State',
    city: 'Bloemfontein',
    judges: ['Linda Botha', 'Thomas Maluleke'],
    classes: ['Elementary 3A', 'Elementary 3B', 'Elementary 3C']
  },
  {
    id: 8,
    name: 'Pietermaritzburg Advanced Series',
    showHoldingBody: 'KwaZulu-Natal Dressage Society',
    showHoldingBodyId: 3,
    venue: 'Pietermaritzburg Equestrian Centre',
    startDate: new Date('2024-09-28'),
    endDate: new Date('2024-09-29'),
    entryClosingDate: new Date('2024-09-14'),
    status: 'Upcoming',
    level: 'Advanced',
    dateCreated: new Date('2024-05-05'),
    isActive: true,
    description: 'High-level advanced competition series',
    maxEntries: 70,
    currentEntries: 42,
    entryFee: 650.00,
    contactEmail: 'advanced@kzndressage.co.za',
    contactPhone: '+27 33 345 7000',
    province: 'KwaZulu-Natal',
    city: 'Pietermaritzburg',
    judges: ['James Peterson', 'Sophie Kruger'],
    classes: ['Advanced 5A', 'Advanced 5B', 'Advanced 5C']
  },
  {
    id: 9,
    name: 'Mbombela Summer Spectacular',
    showHoldingBody: 'Mpumalanga Equestrian Society',
    showHoldingBodyId: 6,
    venue: 'Mbombela Equestrian Complex',
    startDate: new Date('2024-12-14'),
    endDate: new Date('2024-12-15'),
    entryClosingDate: new Date('2024-11-30'),
    status: 'Upcoming',
    level: 'All Levels',
    dateCreated: new Date('2024-06-10'),
    isActive: true,
    description: 'End of year spectacular featuring all levels',
    maxEntries: 130,
    currentEntries: 28,
    entryFee: 400.00,
    contactEmail: 'summer@mpumalangaeq.co.za',
    contactPhone: '+27 13 752 5000',
    province: 'Mpumalanga',
    city: 'Mbombela',
    judges: ['Sophie Kruger', 'Andrew Smith'],
    classes: ['Preliminary 1A', 'Novice 2A', 'Elementary 3A', 'Medium 4A', 'Advanced 5A']
  },
  {
    id: 10,
    name: 'George Garden Route Classic',
    showHoldingBody: 'Western Cape Dressage Association',
    showHoldingBodyId: 1,
    venue: 'George Equestrian Park',
    startDate: new Date('2024-07-20'),
    endDate: new Date('2024-07-21'),
    entryClosingDate: new Date('2024-07-06'),
    status: 'Closed',
    level: 'All Levels',
    dateCreated: new Date('2024-02-28'),
    isActive: true,
    description: 'Scenic competition along the beautiful Garden Route',
    maxEntries: 95,
    currentEntries: 95,
    entryFee: 430.00,
    contactEmail: 'gardenroute@wcdressage.co.za',
    contactPhone: '+27 44 874 4000',
    province: 'Western Cape',
    city: 'George',
    judges: ['Andrew Smith', 'Sarah Mitchell'],
    classes: ['Preliminary 1B', 'Novice 2C', 'Elementary 3B', 'Medium 4C']
  },
  {
    id: 11,
    name: 'Kimberley Diamond Dressage',
    showHoldingBody: 'Northern Cape Equestrian Club',
    showHoldingBodyId: 7,
    venue: 'Kimberley Show Grounds',
    startDate: new Date('2024-05-18'),
    endDate: new Date('2024-05-19'),
    entryClosingDate: new Date('2024-05-04'),
    status: 'Completed',
    level: 'Preliminary',
    dateCreated: new Date('2024-01-08'),
    isActive: false,
    description: 'Regional preliminary competition in the diamond city',
    maxEntries: 75,
    currentEntries: 68,
    entryFee: 360.00,
    contactEmail: 'diamond@ncdressage.co.za',
    contactPhone: '+27 53 831 7000',
    province: 'Northern Cape',
    city: 'Kimberley',
    judges: ['Patricia Nkosi', 'Robert Johnson'],
    classes: ['Preliminary 1A', 'Preliminary 1B']
  },
  {
    id: 12,
    name: 'National Dressage Championships',
    showHoldingBody: 'South African Equestrian Federation',
    showHoldingBodyId: 8,
    venue: 'Johannesburg International Equestrian Centre',
    startDate: new Date('2024-11-22'),
    endDate: new Date('2024-11-24'),
    entryClosingDate: new Date('2024-11-01'),
    status: 'Upcoming',
    level: 'All Levels',
    dateCreated: new Date('2024-01-05'),
    isActive: true,
    description: 'Premier national championship event featuring the best riders in South Africa',
    maxEntries: 200,
    currentEntries: 156,
    entryFee: 950.00,
    contactEmail: 'nationals@saef.co.za',
    contactPhone: '+27 11 468 3236',
    province: 'Gauteng',
    city: 'Johannesburg',
    judges: ['Sarah Mitchell', 'Jennifer Adams', 'Sophie Kruger', 'Andrew Smith'],
    classes: ['Preliminary 1A', 'Novice 2A', 'Elementary 3A', 'Medium 4A', 'Advanced 5A', 'Grand Prix']
  },
  {
    id: 13,
    name: 'Cape Winelands Spring Show',
    showHoldingBody: 'Western Cape Dressage Association',
    showHoldingBodyId: 1,
    venue: 'Paarl Equestrian Estate',
    startDate: new Date('2024-03-15'),
    endDate: new Date('2024-03-16'),
    entryClosingDate: new Date('2024-03-01'),
    status: 'Cancelled',
    level: 'Medium',
    dateCreated: new Date('2023-11-20'),
    isActive: false,
    description: 'Cancelled due to unforeseen circumstances',
    maxEntries: 80,
    currentEntries: 0,
    entryFee: 480.00,
    contactEmail: 'winelands@wcdressage.co.za',
    contactPhone: '+27 21 863 2000',
    province: 'Western Cape',
    city: 'Paarl',
    judges: [],
    classes: []
  }
];

