/**
 * Class Types List Mock Data
 * Realistic test data for the Class Types List feature
 */

import { ClassType } from './class-types-list-type';

/**
 * Mock Class Types Data
 * 15 realistic competition class types
 */
export const CLASS_TYPES: ClassType[] = [
  {
    id: 1,
    name: 'Preliminary Dressage',
    code: 'PRELIM-DR',
    category: 'Dressage',
    description: 'Entry level dressage class for beginners',
    status: 'Active',
    dateCreated: new Date('2020-01-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 5,
    judgesRequired: 1,
    entryFee: 150,
    maxEntries: 30,
    color: '#28a745',
    order: 1,
    entriesCount: 145,
    requirements: [
      'Walk, trot, and canter',
      '20m circles',
      'Free walk on long rein',
      'Simple transitions'
    ],
    notes: 'Most popular entry level class'
  },
  {
    id: 2,
    name: 'Novice Dressage',
    code: 'NOV-DR',
    category: 'Dressage',
    description: 'Developing basic dressage skills',
    status: 'Active',
    dateCreated: new Date('2020-01-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 6,
    judgesRequired: 1,
    entryFee: 175,
    maxEntries: 25,
    color: '#20c997',
    order: 2,
    entriesCount: 128,
    requirements: [
      'Working trot and canter',
      'Lengthened strides',
      '15m circles',
      'Simple changes through trot'
    ],
    notes: 'Building on preliminary skills'
  },
  {
    id: 3,
    name: 'Elementary Dressage',
    code: 'ELEM-DR',
    category: 'Dressage',
    description: 'Introduction to collection and lateral work',
    status: 'Active',
    dateCreated: new Date('2020-01-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 7,
    judgesRequired: 2,
    entryFee: 200,
    maxEntries: 20,
    color: '#17a2b8',
    order: 3,
    entriesCount: 98,
    requirements: [
      'Medium trot and canter',
      'Leg yielding',
      '10m circles',
      'Counter canter'
    ],
    notes: 'Requires 2 judges for accuracy'
  },
  {
    id: 4,
    name: 'Medium Dressage',
    code: 'MED-DR',
    category: 'Dressage',
    description: 'Developing collection and extension',
    status: 'Active',
    dateCreated: new Date('2020-01-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 8,
    judgesRequired: 2,
    entryFee: 225,
    maxEntries: 18,
    color: '#007bff',
    order: 4,
    entriesCount: 76,
    requirements: [
      'Collected and extended gaits',
      'Shoulder-in',
      'Flying changes',
      'Half-pass'
    ],
    notes: 'Significant collection required'
  },
  {
    id: 5,
    name: 'Advanced Dressage',
    code: 'ADV-DR',
    category: 'Dressage',
    description: 'High level collection and precision',
    status: 'Active',
    dateCreated: new Date('2020-01-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 9,
    judgesRequired: 3,
    entryFee: 275,
    maxEntries: 15,
    color: '#6f42c1',
    order: 5,
    entriesCount: 42,
    requirements: [
      'Sequence flying changes',
      'Canter pirouettes',
      'Piaffe and passage',
      'Extended movements'
    ],
    notes: 'Preparation for FEI levels'
  },
  {
    id: 6,
    name: 'Prix St Georges',
    code: 'PSG',
    category: 'Dressage',
    description: 'Entry level FEI competition',
    status: 'Active',
    dateCreated: new Date('2020-01-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 10,
    judgesRequired: 3,
    entryFee: 350,
    maxEntries: 12,
    color: '#e83e8c',
    order: 6,
    entriesCount: 28,
    requirements: [
      'Piaffe and passage',
      'Canter pirouettes',
      'Flying changes every 3rd stride',
      'Extended movements'
    ],
    notes: 'First FEI level competition'
  },
  {
    id: 7,
    name: 'Grand Prix Dressage',
    code: 'GP-DR',
    category: 'Dressage',
    description: 'Highest level of dressage',
    status: 'Active',
    dateCreated: new Date('2020-01-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 12,
    judgesRequired: 5,
    entryFee: 500,
    maxEntries: 10,
    color: '#ffc107',
    order: 7,
    entriesCount: 12,
    requirements: [
      'Tempi changes (every stride)',
      'Piaffe and passage transitions',
      'Canter pirouettes',
      'Maximum collection and extension'
    ],
    notes: 'Olympic and World Championship level'
  },
  {
    id: 8,
    name: 'Young Horse 4 Year Old',
    code: 'YH4',
    category: 'Dressage',
    description: 'Assessment for 4-year-old horses',
    status: 'Active',
    dateCreated: new Date('2021-03-10'),
    isActive: true,
    minAge: 4,
    maxAge: 4,
    duration: 6,
    judgesRequired: 2,
    entryFee: 200,
    maxEntries: 15,
    color: '#3498db',
    order: 8,
    entriesCount: 15,
    requirements: [
      'Walk, trot, canter',
      'Basic balance',
      'Submission',
      'Potential assessment'
    ],
    notes: 'Young horse development program'
  },
  {
    id: 9,
    name: 'Show Jumping 80cm',
    code: 'SJ-80',
    category: 'Show Jumping',
    description: 'Entry level show jumping',
    status: 'Active',
    dateCreated: new Date('2020-02-10'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    minHeight: 75,
    maxHeight: 85,
    duration: 3,
    judgesRequired: 1,
    entryFee: 125,
    maxEntries: 40,
    color: '#ff6b6b',
    order: 9,
    entriesCount: 87,
    requirements: [
      'Basic jumping position',
      'Control at canter',
      'Ability to turn between fences'
    ],
    notes: 'Popular beginner jumping class'
  },
  {
    id: 10,
    name: 'Show Jumping 1.00m',
    code: 'SJ-100',
    category: 'Show Jumping',
    description: 'Intermediate show jumping',
    status: 'Active',
    dateCreated: new Date('2020-02-10'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    minHeight: 95,
    maxHeight: 105,
    duration: 4,
    judgesRequired: 1,
    entryFee: 150,
    maxEntries: 35,
    color: '#ee5a6f',
    order: 10,
    entriesCount: 64,
    requirements: [
      'Secure jumping position',
      'Adjustable canter',
      'Ability to handle related distances'
    ],
    notes: 'Intermediate level jumping'
  },
  {
    id: 11,
    name: 'Show Jumping 1.20m',
    code: 'SJ-120',
    category: 'Show Jumping',
    description: 'Advanced show jumping',
    status: 'Active',
    dateCreated: new Date('2020-02-10'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    minHeight: 115,
    maxHeight: 125,
    duration: 5,
    judgesRequired: 2,
    entryFee: 200,
    maxEntries: 30,
    color: '#c44569',
    order: 11,
    entriesCount: 42,
    requirements: [
      'Advanced jumping technique',
      'Fast adjustments',
      'Technical course handling'
    ],
    notes: 'Advanced level competition'
  },
  {
    id: 12,
    name: 'Eventing Pre-Novice',
    code: 'EV-PN',
    category: 'Eventing',
    description: 'Entry level three-day eventing',
    status: 'Active',
    dateCreated: new Date('2020-03-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 15,
    judgesRequired: 3,
    entryFee: 300,
    maxEntries: 25,
    color: '#f39c12',
    order: 12,
    entriesCount: 38,
    requirements: [
      'Dressage test',
      'Show jumping round',
      'Cross country course',
      'All three phases required'
    ],
    notes: 'Complete three-phase competition'
  },
  {
    id: 13,
    name: 'Eventing Novice',
    code: 'EV-NOV',
    category: 'Eventing',
    description: 'Developing three-day eventing',
    status: 'Active',
    dateCreated: new Date('2020-03-15'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 18,
    judgesRequired: 3,
    entryFee: 350,
    maxEntries: 20,
    color: '#e67e22',
    order: 13,
    entriesCount: 29,
    requirements: [
      'Novice dressage test',
      'Show jumping 1.00m',
      'Cross country with water',
      'All three phases required'
    ],
    notes: 'Intermediate eventing level'
  },
  {
    id: 14,
    name: 'Working Equitation Ease of Handling',
    code: 'WE-EOH',
    category: 'Working Equitation',
    description: 'Technical obstacle course',
    status: 'Active',
    dateCreated: new Date('2022-05-20'),
    isActive: true,
    minAge: 0,
    maxAge: 100,
    duration: 8,
    judgesRequired: 2,
    entryFee: 175,
    maxEntries: 20,
    color: '#16a085',
    order: 14,
    entriesCount: 22,
    requirements: [
      'Navigate obstacles',
      'Precision and control',
      'Traditional tack allowed'
    ],
    notes: 'Growing discipline in South Africa'
  },
  {
    id: 15,
    name: 'Combined Training',
    code: 'CT',
    category: 'Combined Training',
    description: 'Dressage and show jumping combination',
    status: 'Inactive',
    dateCreated: new Date('2019-08-10'),
    isActive: false,
    minAge: 0,
    maxAge: 100,
    duration: 10,
    judgesRequired: 2,
    entryFee: 200,
    maxEntries: 25,
    color: '#95a5a6',
    order: 15,
    entriesCount: 8,
    requirements: [
      'Dressage test',
      'Show jumping round',
      'Combined scoring'
    ],
    notes: 'Currently under review for 2026 season'
  }
];
