# Generated by Django 5.2 on 2026-04-01 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the breed",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Breed name (e.g., Warmblood, Thoroughbred)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the breed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this breed is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Breed",
                "verbose_name_plural": "Breeds",
                "db_table": "horse_breeds",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the classification",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Classification name (e.g., Pony, Horse)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the classification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this classification is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Classification",
                "verbose_name_plural": "Classifications",
                "db_table": "horse_classifications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HorseColor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the color",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Color name (e.g., Bay, Black, Chestnut)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Color code or hex value (optional)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this color is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Horse Color",
                "verbose_name_plural": "Horse Colors",
                "db_table": "horse_colors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BreedType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the breed type",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Breed type name", max_length=100)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this breed type is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breed",
                    models.ForeignKey(
                        help_text="Parent breed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breed_types",
                        to="horse.breed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breed Type",
                "verbose_name_plural": "Breed Types",
                "db_table": "horse_breed_types",
                "ordering": ["breed__name", "name"],
                "unique_together": {("breed", "name")},
            },
        ),
        migrations.CreateModel(
            name="Horse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the horse",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Horse name", max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MARE", "Mare"),
                            ("STALLION", "Stallion"),
                            ("GELDING", "Gelding"),
                        ],
                        help_text="Horse gender",
                        max_length=20,
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        help_text="Passport number", max_length=100, unique=True
                    ),
                ),
                (
                    "microchip_number",
                    models.CharField(
                        help_text="Microchip number", max_length=100, unique=True
                    ),
                ),
                ("date_of_birth", models.DateField(help_text="Date of birth")),
                (
                    "country",
                    models.CharField(help_text="Country of origin", max_length=100),
                ),
                (
                    "sire",
                    models.CharField(
                        blank=True, help_text="Sire (father) name", max_length=200
                    ),
                ),
                (
                    "dam",
                    models.CharField(
                        blank=True, help_text="Dam (mother) name", max_length=200
                    ),
                ),
                (
                    "sire_of_dam",
                    models.CharField(
                        blank=True,
                        help_text="Sire of dam (maternal grandfather)",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("BANNED", "Banned"),
                            ("RETIRED", "Retired"),
                            ("INACTIVE", "Inactive"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Horse status",
                        max_length=20,
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the horse is banned",
                    ),
                ),
                (
                    "banned_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when banned", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breed",
                    models.ForeignKey(
                        help_text="Horse breed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horses",
                        to="horse.breed",
                    ),
                ),
                (
                    "breed_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific breed type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horses",
                        to="horse.breedtype",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        help_text="Horse color",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horses",
                        to="horse.horsecolor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horse",
                "verbose_name_plural": "Horses",
                "db_table": "horses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HorseDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the document",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "Passport"),
                            ("REGISTRATION", "Registration"),
                            ("VACCINATION", "Vaccination"),
                            ("MEDICAL", "Medical"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of document",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=200)),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                ("file_url", models.URLField(help_text="URL to the document file")),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the document was uploaded",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Document expiry date", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "horse",
                    models.ForeignKey(
                        help_text="Horse associated with this document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="horse.horse",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_horse_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Horse Document",
                "verbose_name_plural": "Horse Documents",
                "db_table": "horse_documents",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="HorseVaccination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the vaccination",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vaccination_type",
                    models.CharField(
                        choices=[
                            ("FLU", "Influenza (Flu)"),
                            ("AHS", "African Horse Sickness"),
                            ("TETANUS", "Tetanus"),
                            ("RABIES", "Rabies"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of vaccination",
                        max_length=20,
                    ),
                ),
                ("vaccination_date", models.DateField(help_text="Date of vaccination")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Vaccination expiry date", null=True
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, help_text="Vaccine batch number", max_length=100
                    ),
                ),
                (
                    "veterinarian",
                    models.CharField(
                        blank=True,
                        help_text="Veterinarian who administered the vaccination",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "horse",
                    models.ForeignKey(
                        help_text="Horse receiving the vaccination",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="horse.horse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horse Vaccination",
                "verbose_name_plural": "Horse Vaccinations",
                "db_table": "horse_vaccinations",
                "ordering": ["-vaccination_date"],
            },
        ),
        migrations.CreateModel(
            name="HorseAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the account",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_ref",
                    models.CharField(
                        help_text="Reference to account (placeholder for ForeignKey)",
                        max_length=100,
                    ),
                ),
                (
                    "year_ref",
                    models.CharField(
                        help_text="Reference to year (placeholder for ForeignKey)",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Account amount", max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classification",
                    models.ForeignKey(
                        help_text="Horse classification for this account",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horse_accounts",
                        to="horse.classification",
                    ),
                ),
                (
                    "horse",
                    models.ForeignKey(
                        help_text="Horse associated with this account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="horse.horse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horse Account",
                "verbose_name_plural": "Horse Accounts",
                "db_table": "horse_accounts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["horse", "-created_at"],
                        name="horse_accou_horse_i_6cf9c8_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="horse",
            index=models.Index(
                fields=["passport_number"], name="horses_passpor_dcec93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horse",
            index=models.Index(
                fields=["microchip_number"], name="horses_microch_d20ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horse",
            index=models.Index(fields=["status"], name="horses_status_264d64_idx"),
        ),
        migrations.AddIndex(
            model_name="horse",
            index=models.Index(fields=["is_banned"], name="horses_is_bann_d7a0d3_idx"),
        ),
        migrations.AddIndex(
            model_name="horsedocument",
            index=models.Index(
                fields=["horse", "-upload_date"], name="horse_docum_horse_i_fabb19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horsedocument",
            index=models.Index(
                fields=["document_type"], name="horse_docum_documen_4ede03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horsevaccination",
            index=models.Index(
                fields=["horse", "-vaccination_date"],
                name="horse_vacci_horse_i_f5c9c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="horsevaccination",
            index=models.Index(
                fields=["vaccination_type"], name="horse_vacci_vaccina_ababf8_idx"
            ),
        ),
    ]
