# Generated by Django 5.2 on 2026-04-02 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("horse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="horsedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_horse_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="horsevaccination",
            name="horse",
            field=models.ForeignKey(
                help_text="Horse receiving the vaccination",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vaccinations",
                to="horse.horse",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="breedtype",
            unique_together={("breed", "name")},
        ),
        migrations.AddIndex(
            model_name="horseaccount",
            index=models.Index(
                fields=["horse", "-created_at"], name="horse_accou_horse_i_6cf9c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horse",
            index=models.Index(
                fields=["passport_number"], name="horses_passpor_dcec93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horse",
            index=models.Index(
                fields=["microchip_number"], name="horses_microch_d20ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horse",
            index=models.Index(fields=["status"], name="horses_status_264d64_idx"),
        ),
        migrations.AddIndex(
            model_name="horse",
            index=models.Index(fields=["is_banned"], name="horses_is_bann_d7a0d3_idx"),
        ),
        migrations.AddIndex(
            model_name="horsedocument",
            index=models.Index(
                fields=["horse", "-upload_date"], name="horse_docum_horse_i_fabb19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horsedocument",
            index=models.Index(
                fields=["document_type"], name="horse_docum_documen_4ede03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horsevaccination",
            index=models.Index(
                fields=["horse", "-vaccination_date"],
                name="horse_vacci_horse_i_f5c9c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="horsevaccination",
            index=models.Index(
                fields=["vaccination_type"], name="horse_vacci_vaccina_ababf8_idx"
            ),
        ),
    ]
