# Generated by Django 5.2 on 2026-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Name of the membership type (e.g., "Rider Membership")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the membership type"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this membership type is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or information about this membership type",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the membership type was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the membership type was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Type",
                "verbose_name_plural": "Membership Types",
                "db_table": "memberships",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="memberships_name_62653b_idx"),
                    models.Index(
                        fields=["is_active"], name="memberships_is_acti_eec862_idx"
                    ),
                ],
            },
        ),
    ]
