# Generated by Django 5.2 on 2026-03-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
        ("years", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Name of the subscription type (e.g., "Senior Adult Competitive")',
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the subscription type"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subscription fee (excluding VAT)",
                        max_digits=10,
                    ),
                ),
                (
                    "fee_including_vat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subscription fee including VAT",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this subscription type is currently active",
                    ),
                ),
                (
                    "is_recreational",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a recreational subscription type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or information about this subscription",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the subscription was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the subscription was last updated",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        help_text="Membership type this subscription belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="membership.membership",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        help_text="Competition year this subscription applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="years.year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
                "ordering": ["year", "membership", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="subscriptio_name_452f0e_idx"),
                    models.Index(
                        fields=["year"], name="subscriptio_year_id_59e376_idx"
                    ),
                    models.Index(
                        fields=["membership"], name="subscriptio_members_ca9e4c_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="subscriptio_is_acti_238e40_idx"
                    ),
                    models.Index(
                        fields=["year", "membership"],
                        name="subscriptio_year_id_4be16d_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("fee__gte", 0)),
                        name="fee_non_negative",
                        violation_error_message="Fee must be non-negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fee_including_vat__gte", models.F("fee"))),
                        name="fee_vat_gte_fee",
                        violation_error_message="Fee including VAT must be greater than or equal to fee",
                    ),
                ],
            },
        ),
    ]
