/**
 * Districts List Mock Data
 * Realistic test data for the Districts List feature
 */

import { District } from './districts-list-type';

/**
 * Mock Districts Data
 * 15 realistic South African dressage districts
 */
export const DISTRICTS: District[] = [
  {
    id: 1,
    name: 'Gauteng North District',
    code: 'GTN',
    province: 'Gauteng',
    description: 'Northern Gauteng region covering Pretoria, Centurion, and surrounding areas',
    contactPerson: 'Sarah Mitchell',
    email: 'sarah.mitchell@dressagesa.com',
    phone: '+27 12 345 6789',
    status: 'Active',
    dateCreated: new Date('2015-03-15'),
    isActive: true,
    clubsCount: 12,
    membersCount: 245,
    address: '123 Dressage Road, Centurion',
    city: 'Pretoria',
    postalCode: '0157',
    website: 'https://www.gauteng-north-dressage.co.za'
  },
  {
    id: 2,
    name: 'Gauteng South District',
    code: 'GTS',
    province: 'Gauteng',
    description: 'Southern Gauteng region including Johannesburg, Sandton, and Randburg',
    contactPerson: 'Michael Thompson',
    email: 'michael.thompson@dressagesa.com',
    phone: '+27 11 234 5678',
    status: 'Active',
    dateCreated: new Date('2015-03-15'),
    isActive: true,
    clubsCount: 18,
    membersCount: 387,
    address: '456 Equestrian Avenue, Sandton',
    city: 'Johannesburg',
    postalCode: '2191',
    website: 'https://www.gauteng-south-dressage.co.za'
  },
  {
    id: 3,
    name: 'Western Cape District',
    code: 'WCP',
    province: 'Western Cape',
    description: 'Western Cape region covering Cape Town, Stellenbosch, and surrounding areas',
    contactPerson: 'Amanda Botha',
    email: 'amanda.botha@dressagesa.com',
    phone: '+27 21 456 7890',
    status: 'Active',
    dateCreated: new Date('2014-06-20'),
    isActive: true,
    clubsCount: 15,
    membersCount: 312,
    address: '789 Winelands Road, Stellenbosch',
    city: 'Cape Town',
    postalCode: '7600',
    website: 'https://www.western-cape-dressage.co.za'
  },
  {
    id: 4,
    name: 'KwaZulu-Natal Coastal District',
    code: 'KZC',
    province: 'KwaZulu-Natal',
    description: 'Coastal KZN region including Durban, Umhlanga, and surrounding areas',
    contactPerson: 'Jennifer van der Merwe',
    email: 'jennifer.vandermerwe@dressagesa.com',
    phone: '+27 31 567 8901',
    status: 'Active',
    dateCreated: new Date('2016-01-10'),
    isActive: true,
    clubsCount: 10,
    membersCount: 198,
    address: '321 Coastal Drive, Umhlanga',
    city: 'Durban',
    postalCode: '4001',
    website: 'https://www.kzn-coastal-dressage.co.za'
  },
  {
    id: 5,
    name: 'KwaZulu-Natal Midlands District',
    code: 'KZM',
    province: 'KwaZulu-Natal',
    description: 'Midlands region covering Pietermaritzburg, Howick, and surrounding areas',
    contactPerson: 'Peter Naidoo',
    email: 'peter.naidoo@dressagesa.com',
    phone: '+27 33 678 9012',
    status: 'Active',
    dateCreated: new Date('2016-01-10'),
    isActive: true,
    clubsCount: 8,
    membersCount: 156,
    address: '654 Midlands Road, Howick',
    city: 'Pietermaritzburg',
    postalCode: '3245'
  },
  {
    id: 6,
    name: 'Eastern Cape District',
    code: 'ECP',
    province: 'Eastern Cape',
    description: 'Eastern Cape region including Port Elizabeth, East London, and surrounding areas',
    contactPerson: 'James Koopman',
    email: 'james.koopman@dressagesa.com',
    phone: '+27 41 789 0123',
    status: 'Active',
    dateCreated: new Date('2017-05-18'),
    isActive: true,
    clubsCount: 6,
    membersCount: 124,
    address: '987 Marine Drive, Summerstrand',
    city: 'Port Elizabeth',
    postalCode: '6001'
  },
  {
    id: 7,
    name: 'Free State District',
    code: 'FST',
    province: 'Free State',
    description: 'Free State region covering Bloemfontein and surrounding areas',
    contactPerson: 'Annelie Pretorius',
    email: 'annelie.pretorius@dressagesa.com',
    phone: '+27 51 890 1234',
    status: 'Active',
    dateCreated: new Date('2018-02-22'),
    isActive: true,
    clubsCount: 5,
    membersCount: 98,
    address: '147 Naval Hill Road, Bloemfontein',
    city: 'Bloemfontein',
    postalCode: '9301'
  },
  {
    id: 8,
    name: 'Mpumalanga District',
    code: 'MPU',
    province: 'Mpumalanga',
    description: 'Mpumalanga region including Nelspruit, White River, and Lowveld areas',
    contactPerson: 'Thandi Mthembu',
    email: 'thandi.mthembu@dressagesa.com',
    phone: '+27 13 901 2345',
    status: 'Active',
    dateCreated: new Date('2019-08-17'),
    isActive: true,
    clubsCount: 4,
    membersCount: 76,
    address: '258 White River Road, Nelspruit',
    city: 'Nelspruit',
    postalCode: '1200'
  },
  {
    id: 9,
    name: 'Limpopo District',
    code: 'LIM',
    province: 'Limpopo',
    description: 'Limpopo region covering Polokwane and surrounding areas',
    contactPerson: 'David Kruger',
    email: 'david.kruger@dressagesa.com',
    phone: '+27 15 012 3456',
    status: 'Inactive',
    dateCreated: new Date('2020-11-30'),
    isActive: false,
    clubsCount: 2,
    membersCount: 34,
    address: '369 Polokwane Road, Polokwane',
    city: 'Polokwane',
    postalCode: '0699'
  },
  {
    id: 10,
    name: 'North West District',
    code: 'NWT',
    province: 'North West',
    description: 'North West region including Rustenburg, Potchefstroom, and surrounding areas',
    contactPerson: 'Lisa Marais',
    email: 'lisa.marais@dressagesa.com',
    phone: '+27 14 123 4567',
    status: 'Active',
    dateCreated: new Date('2017-09-05'),
    isActive: true,
    clubsCount: 5,
    membersCount: 89,
    address: '741 Rustenburg Road, Rustenburg',
    city: 'Rustenburg',
    postalCode: '0299'
  },
  {
    id: 11,
    name: 'Northern Cape District',
    code: 'NCP',
    province: 'Northern Cape',
    description: 'Northern Cape region covering Kimberley and surrounding areas',
    contactPerson: 'Robert Wilson',
    email: 'robert.wilson@dressagesa.com',
    phone: '+27 53 234 5678',
    status: 'Active',
    dateCreated: new Date('2018-04-12'),
    isActive: true,
    clubsCount: 3,
    membersCount: 45,
    address: '852 Diamond Road, Kimberley',
    city: 'Kimberley',
    postalCode: '8301'
  },
  {
    id: 12,
    name: 'Garden Route District',
    code: 'GRD',
    province: 'Western Cape',
    description: 'Garden Route region including George, Knysna, and Plettenberg Bay',
    contactPerson: 'Emma Fourie',
    email: 'emma.fourie@dressagesa.com',
    phone: '+27 44 345 6789',
    status: 'Active',
    dateCreated: new Date('2016-09-25'),
    isActive: true,
    clubsCount: 7,
    membersCount: 134,
    address: '963 Garden Route Road, George',
    city: 'George',
    postalCode: '6529',
    website: 'https://www.garden-route-dressage.co.za'
  },
  {
    id: 13,
    name: 'Overberg District',
    code: 'OVB',
    province: 'Western Cape',
    description: 'Overberg region including Hermanus, Caledon, and surrounding areas',
    contactPerson: 'Catherine Smit',
    email: 'catherine.smit@dressagesa.com',
    phone: '+27 28 456 7890',
    status: 'Active',
    dateCreated: new Date('2017-11-08'),
    isActive: true,
    clubsCount: 4,
    membersCount: 67,
    address: '159 Overberg Road, Hermanus',
    city: 'Hermanus',
    postalCode: '7200'
  },
  {
    id: 14,
    name: 'Gauteng East District',
    code: 'GTE',
    province: 'Gauteng',
    description: 'Eastern Gauteng region including Benoni, Boksburg, and East Rand areas',
    contactPerson: 'Nicole van Zyl',
    email: 'nicole.vanzyl@dressagesa.com',
    phone: '+27 11 567 8901',
    status: 'Active',
    dateCreated: new Date('2019-03-14'),
    isActive: true,
    clubsCount: 9,
    membersCount: 178,
    address: '357 East Rand Road, Benoni',
    city: 'Benoni',
    postalCode: '1501'
  },
  {
    id: 15,
    name: 'West Coast District',
    code: 'WCS',
    province: 'Western Cape',
    description: 'West Coast region including Langebaan, Saldanha, and surrounding areas',
    contactPerson: 'Dr. Heinrich Muller',
    email: 'heinrich.muller@dressagesa.com',
    phone: '+27 22 678 9012',
    status: 'Inactive',
    dateCreated: new Date('2020-06-19'),
    isActive: false,
    clubsCount: 2,
    membersCount: 28,
    address: '753 West Coast Road, Langebaan',
    city: 'Langebaan',
    postalCode: '7357'
  }
];

