/**
 * Clubs List Mock Data
 * Realistic test data for the Clubs List feature
 */

import { Club } from './clubs-list-type';

/**
 * Mock Clubs Data
 * 15 realistic Club organizations with diverse locations and statuses
 */
export const CLUBS: Club[] = [
  {
    id: 1,
    name: 'Cape Town Dressage Club',
    registrationNumber: 'CLB-2019-001',
    logo: 'assets/images/organizations/club-1.jpg',
    province: 'Western Cape',
    city: 'Cape Town',
    address: '45 Equestrian Lane, Constantia',
    postalCode: '7806',
    contactPerson: 'Emma Richardson',
    email: 'info@capetowndressage.dressage.co.za',
    phone: '+27 21 794 3000',
    status: 'Active',
    dateCreated: new Date('2019-03-15'),
    isActive: true,
    memberCount: 85
  },
  {
    id: 2,
    name: 'Johannesburg Equestrian Society',
    registrationNumber: 'CLB-2018-015',
    logo: 'assets/images/organizations/club-2.jpg',
    province: 'Gauteng',
    city: 'Johannesburg',
    address: '123 Riding Road, Sandton',
    postalCode: '2196',
    contactPerson: 'Michael van der Berg',
    email: 'contact@jhbequestriansociety.dressage.com',
    phone: '+27 11 883 5000',
    status: 'Active',
    dateCreated: new Date('2018-06-20'),
    isActive: true,
    memberCount: 120
  },
  {
    id: 3,
    name: 'Durban Riding Academy',
    registrationNumber: 'CLB-2020-008',
    logo: 'assets/images/organizations/club-3.jpg',
    province: 'KwaZulu-Natal',
    city: 'Durban',
    address: '67 Coastal Drive, Umhlanga',
    postalCode: '4319',
    contactPerson: 'Sarah Naidoo',
    email: 'admin@durbanriding.dressage.co.za',
    phone: '+27 31 561 4000',
    status: 'Active',
    dateCreated: new Date('2020-01-10'),
    isActive: true,
    memberCount: 95
  },
  {
    id: 4,
    name: 'Pretoria Dressage Club',
    registrationNumber: 'CLB-2017-022',
    logo: 'assets/images/organizations/club-4.jpg',
    province: 'Gauteng',
    city: 'Pretoria',
    address: '89 Academy Street, Waterkloof',
    postalCode: '0181',
    contactPerson: 'David Kruger',
    email: 'info@pretoriadressage.dressage.com',
    phone: '+27 12 346 8000',
    status: 'Active',
    dateCreated: new Date('2017-09-05'),
    isActive: true,
    memberCount: 110
  },
  {
    id: 5,
    name: 'Stellenbosch Equestrian Club',
    registrationNumber: 'CLB-2019-012',
    logo: 'assets/images/organizations/club-5.jpg',
    province: 'Western Cape',
    city: 'Stellenbosch',
    address: '34 Winery Lane, Stellenbosch',
    postalCode: '7600',
    contactPerson: 'Lisa Botha',
    email: 'contact@stellenboscheq.dressage.co.za',
    phone: '+27 21 887 2000',
    status: 'Inactive',
    dateCreated: new Date('2019-07-22'),
    isActive: false,
    memberCount: 45
  },
  {
    id: 6,
    name: 'Port Elizabeth Riding Club',
    registrationNumber: 'CLB-2018-030',
    logo: 'assets/images/organizations/club-1.jpg',
    province: 'Eastern Cape',
    city: 'Gqeberha',
    address: '56 Beachfront Road, Summerstrand',
    postalCode: '6001',
    contactPerson: 'Robert Malan',
    email: 'info@periding.dressage.com',
    phone: '+27 41 583 3000',
    status: 'Active',
    dateCreated: new Date('2018-11-18'),
    isActive: true,
    memberCount: 78
  },
  {
    id: 7,
    name: 'Bloemfontein Equestrian Association',
    registrationNumber: 'CLB-2020-005',
    logo: 'assets/images/organizations/club-2.jpg',
    province: 'Free State',
    city: 'Bloemfontein',
    address: '12 Show Road, Westdene',
    postalCode: '9301',
    contactPerson: 'Patricia Steyn',
    email: 'admin@bloemeq.dressage.co.za',
    phone: '+27 51 447 9000',
    status: 'Active',
    dateCreated: new Date('2020-04-12'),
    isActive: true,
    memberCount: 62
  },
  {
    id: 8,
    name: 'Pietermaritzburg Dressage Society',
    registrationNumber: 'CLB-2019-018',
    logo: 'assets/images/organizations/club-3.jpg',
    province: 'KwaZulu-Natal',
    city: 'Pietermaritzburg',
    address: '78 Midlands Avenue, Scottsville',
    postalCode: '3201',
    contactPerson: 'James Peterson',
    email: 'contact@pmbdressage.dressage.com',
    phone: '+27 33 345 7000',
    status: 'Active',
    dateCreated: new Date('2019-10-08'),
    isActive: true,
    memberCount: 55
  },
  {
    id: 9,
    name: 'Nelspruit Riding Club',
    registrationNumber: 'CLB-2021-003',
    logo: 'assets/images/organizations/club-4.jpg',
    province: 'Mpumalanga',
    city: 'Mbombela',
    address: '23 Lowveld Street, West Acres',
    postalCode: '1200',
    contactPerson: 'Sophie Marais',
    email: 'info@nelspruitriding.dressage.co.za',
    phone: '+27 13 752 5000',
    status: 'Active',
    dateCreated: new Date('2021-02-14'),
    isActive: true,
    memberCount: 48
  },
  {
    id: 10,
    name: 'Polokwane Equestrian Club',
    registrationNumber: 'CLB-2018-025',
    logo: 'assets/images/organizations/club-5.jpg',
    province: 'Limpopo',
    city: 'Polokwane',
    address: '90 Agricultural Road, Bendor',
    postalCode: '0699',
    contactPerson: 'Thomas Maluleke',
    email: 'admin@polokwaneeq.dressage.com',
    phone: '+27 15 297 6000',
    status: 'Inactive',
    dateCreated: new Date('2018-08-30'),
    isActive: false,
    memberCount: 32
  },
  {
    id: 11,
    name: 'Kimberley Diamond Riding Club',
    registrationNumber: 'CLB-2020-011',
    logo: 'assets/images/organizations/club-1.jpg',
    province: 'Northern Cape',
    city: 'Kimberley',
    address: '45 Diamond Avenue, Beaconsfield',
    postalCode: '8301',
    contactPerson: 'Catherine Nkosi',
    email: 'contact@kimberleyriding.dressage.co.za',
    phone: '+27 53 831 7000',
    status: 'Active',
    dateCreated: new Date('2020-06-25'),
    isActive: true,
    memberCount: 41
  },
  {
    id: 12,
    name: 'George Garden Route Equestrian',
    registrationNumber: 'CLB-2019-009',
    logo: 'assets/images/organizations/club-2.jpg',
    province: 'Western Cape',
    city: 'George',
    address: '67 Garden Route Drive, Heatherlands',
    postalCode: '6529',
    contactPerson: 'Andrew Smith',
    email: 'info@georgeeq.dressage.com',
    phone: '+27 44 874 4000',
    status: 'Active',
    dateCreated: new Date('2019-05-17'),
    isActive: true,
    memberCount: 68
  }
];

