# Generated by Django 5.2 on 2026-03-31 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the refresh token",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.TextField(
                        db_index=True,
                        help_text="The JWT refresh token string",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the refresh token was created",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the refresh token expires"),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the token has been revoked",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="When the token was revoked", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which the token was created",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this refresh token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
                "db_table": "auth_refresh_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "is_revoked"],
                        name="auth_refres_token_a1a040_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="auth_refres_user_id_be59d5_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="auth_refres_expires_4ad26b_idx"
                    ),
                ],
            },
        ),
    ]
