# Generated by Django 5.2 on 2026-04-02 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the refresh token",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.TextField(
                        db_index=True,
                        help_text="The JWT refresh token string",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the refresh token was created",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the refresh token expires"),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the token has been revoked",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="When the token was revoked", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which the token was created",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
                "db_table": "auth_refresh_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
