# Generated by Django 5.2 on 2026-04-02 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this refresh token",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_refresh_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["token", "is_revoked"], name="auth_refres_token_a1a040_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["user", "-created_at"], name="auth_refres_user_id_be59d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["expires_at"], name="auth_refres_expires_4ad26b_idx"
            ),
        ),
    ]
