/**
 * Show Holding Body List Mock Data
 * Realistic test data for the Show Holding Bodies List feature
 */

import { ShowHoldingBody } from './show-holding-body-list-type';

/**
 * Mock Show Holding Bodies Data
 * 15 realistic Show Holding Body organizations with diverse locations and statuses
 */
export const SHOW_HOLDING_BODIES: ShowHoldingBody[] = [
  {
    id: 1,
    name: 'Cape Town Equestrian Centre',
    registrationNumber: 'SHB-2020-001',
    logo: 'assets/images/organizations/org-1.jpg',
    province: 'Western Cape',
    city: 'Cape Town',
    address: '123 Equestrian Drive, Constantia',
    postalCode: '7806',
    contactPerson: 'Sarah Mitchell',
    email: 'info@capeequestrian.shyft.com',
    phone: '+27 21 794 5000',
    status: 'Active',
    dateCreated: new Date('2020-03-15'),
    isActive: true
  },
  {
    id: 2,
    name: 'Johannesburg Show Grounds',
    registrationNumber: 'SHB-2019-015',
    logo: 'assets/images/organizations/org-2.jpg',
    province: 'Gauteng',
    city: 'Johannesburg',
    address: '45 Showground Avenue, Sandton',
    postalCode: '2196',
    contactPerson: 'Michael Thompson',
    email: 'contact@jhbshowgrounds.byteorbit.com',
    phone: '+27 11 883 6000',
    status: 'Active',
    dateCreated: new Date('2019-06-20'),
    isActive: true
  },
  {
    id: 3,
    name: 'Durban Equestrian Park',
    registrationNumber: 'SHB-2021-008',
    logo: 'assets/images/organizations/org-3.jpg',
    province: 'KwaZulu-Natal',
    city: 'Durban',
    address: '78 Coastal Road, Umhlanga',
    postalCode: '4319',
    contactPerson: 'Jennifer Adams',
    email: 'admin@durbanequestrian.shyft.com',
    phone: '+27 31 561 2000',
    status: 'Active',
    dateCreated: new Date('2021-01-10'),
    isActive: true
  },
  {
    id: 4,
    name: 'Pretoria Dressage Academy',
    registrationNumber: 'SHB-2018-022',
    logo: 'assets/images/organizations/org-4.jpg',
    province: 'Gauteng',
    city: 'Pretoria',
    address: '12 Academy Street, Waterkloof',
    postalCode: '0181',
    contactPerson: 'David Williams',
    email: 'info@pretoriadressage.byteorbit.com',
    phone: '+27 12 346 7000',
    status: 'Active',
    dateCreated: new Date('2018-09-05'),
    isActive: true
  },
  {
    id: 5,
    name: 'Stellenbosch Riding Club',
    registrationNumber: 'SHB-2020-012',
    logo: 'assets/images/organizations/org-5.jpg',
    province: 'Western Cape',
    city: 'Stellenbosch',
    address: '56 Winery Lane, Stellenbosch',
    postalCode: '7600',
    contactPerson: 'Emma van der Merwe',
    email: 'contact@stellenboschrc.shyft.com',
    phone: '+27 21 887 3000',
    status: 'Inactive',
    dateCreated: new Date('2020-07-22'),
    isActive: false
  },
  {
    id: 6,
    name: 'Port Elizabeth Equestrian Society',
    registrationNumber: 'SHB-2019-030',
    logo: 'assets/images/organizations/org-1.jpg',
    province: 'Eastern Cape',
    city: 'Gqeberha',
    address: '34 Beachfront Drive, Summerstrand',
    postalCode: '6001',
    contactPerson: 'Robert Johnson',
    email: 'info@peequestrian.byteorbit.com',
    phone: '+27 41 583 2000',
    status: 'Active',
    dateCreated: new Date('2019-11-18'),
    isActive: true
  },
  {
    id: 7,
    name: 'Bloemfontein Horse Show Association',
    registrationNumber: 'SHB-2021-005',
    logo: 'assets/images/organizations/org-2.jpg',
    province: 'Free State',
    city: 'Bloemfontein',
    address: '89 Show Road, Westdene',
    postalCode: '9301',
    contactPerson: 'Linda Botha',
    email: 'admin@bloemequestrianshow.shyft.com',
    phone: '+27 51 447 8000',
    status: 'Active',
    dateCreated: new Date('2021-04-12'),
    isActive: true
  },
  {
    id: 8,
    name: 'Pietermaritzburg Riding Centre',
    registrationNumber: 'SHB-2020-018',
    logo: 'assets/images/organizations/org-3.jpg',
    province: 'KwaZulu-Natal',
    city: 'Pietermaritzburg',
    address: '23 Midlands Avenue, Scottsville',
    postalCode: '3201',
    contactPerson: 'James Peterson',
    email: 'contact@pmbriding.byteorbit.com',
    phone: '+27 33 345 6000',
    status: 'Active',
    dateCreated: new Date('2020-10-08'),
    isActive: true
  },
  {
    id: 9,
    name: 'Nelspruit Equestrian Club',
    registrationNumber: 'SHB-2022-003',
    logo: 'assets/images/organizations/org-4.jpg',
    province: 'Mpumalanga',
    city: 'Mbombela',
    address: '67 Lowveld Street, West Acres',
    postalCode: '1200',
    contactPerson: 'Sophie Kruger',
    email: 'info@nelspruitequestrian.shyft.com',
    phone: '+27 13 752 4000',
    status: 'Active',
    dateCreated: new Date('2022-02-14'),
    isActive: true
  },
  {
    id: 10,
    name: 'Polokwane Show Society',
    registrationNumber: 'SHB-2019-025',
    logo: 'assets/images/organizations/org-5.jpg',
    province: 'Limpopo',
    city: 'Polokwane',
    address: '45 Agricultural Road, Bendor',
    postalCode: '0699',
    contactPerson: 'Thomas Maluleke',
    email: 'admin@polokwaneshow.byteorbit.com',
    phone: '+27 15 297 5000',
    status: 'Inactive',
    dateCreated: new Date('2019-08-30'),
    isActive: false
  },
  {
    id: 11,
    name: 'Kimberley Diamond Equestrian',
    registrationNumber: 'SHB-2021-011',
    logo: 'assets/images/organizations/org-1.jpg',
    province: 'Northern Cape',
    city: 'Kimberley',
    address: '12 Diamond Avenue, Beaconsfield',
    postalCode: '8301',
    contactPerson: 'Patricia Nkosi',
    email: 'contact@kimberleyequestrian.shyft.com',
    phone: '+27 53 831 6000',
    status: 'Active',
    dateCreated: new Date('2021-06-25'),
    isActive: true
  },
  {
    id: 12,
    name: 'George Garden Route Riding',
    registrationNumber: 'SHB-2020-009',
    logo: 'assets/images/organizations/org-2.jpg',
    province: 'Western Cape',
    city: 'George',
    address: '78 Garden Route Drive, Heatherlands',
    postalCode: '6529',
    contactPerson: 'Andrew Smith',
    email: 'info@georgeriding.byteorbit.com',
    phone: '+27 44 874 3000',
    status: 'Active',
    dateCreated: new Date('2020-05-17'),
    isActive: true
  }
];

