# Generated by Django 5.2 on 2026-04-02 14:04

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Payment method name", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Unique slug code for the payment method", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the payment method"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this payment method is active"
                    ),
                ),
                (
                    "allow_for_entries",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this payment method can be used for competition entries",
                    ),
                ),
                (
                    "allow_for_renewals",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this payment method can be used for membership renewals",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "payment_methods",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="payment_met_code_b70caa_idx"),
                    models.Index(
                        fields=["is_active"], name="payment_met_is_acti_395fa6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Province name", max_length=100, unique=True
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        help_text="Country this province belongs to", max_length=2
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this province is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "db_table": "provinces",
                "ordering": ["country", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="provinces_name_20abeb_idx"),
                    models.Index(
                        fields=["country"], name="provinces_country_57fd41_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="provinces_is_acti_367ff8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VatCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="VAT code name (e.g., 'Standard VAT', 'Zero-rated')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique VAT code identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="VAT percentage (e.g., 15.00 for 15%)",
                        max_digits=5,
                    ),
                ),
                (
                    "is_applicable_to_membership",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this VAT code applies to membership fees",
                    ),
                ),
                (
                    "is_applicable_to_competitions",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this VAT code applies to competition entries",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default VAT code"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this VAT code is active"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this VAT code"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "VAT Code",
                "verbose_name_plural": "VAT Codes",
                "db_table": "vat_codes",
                "ordering": ["-is_default", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="vat_codes_code_737fbd_idx"),
                    models.Index(
                        fields=["is_default"], name="vat_codes_is_defa_024477_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="vat_codes_is_acti_e4fd2b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="School name", max_length=255, unique=True
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, help_text="Primary contact person", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=50
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Physical address")),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        help_text="Current status of the school",
                        max_length=20,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="School website URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="School description"),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        help_text="School logo",
                        null=True,
                        upload_to="school_logos/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        help_text="Province where the school is located",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schools",
                        to="common.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "schools",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="schools_name_2838ce_idx"),
                    models.Index(fields=["status"], name="schools_status_0f17fc_idx"),
                    models.Index(
                        fields=["province"], name="schools_provinc_3beae7_idx"
                    ),
                ],
            },
        ),
    ]
