/**
 * Schools List Mock Data
 * Realistic test data for the Schools List feature
 */

import { School } from './schools-list-type';

/**
 * Mock Schools Data
 * 15 realistic South African riding schools and training facilities
 */
export const SCHOOLS: School[] = [
  {
    id: 1,
    name: 'Kyalami Equestrian Park',
    type: 'Competition Venue',
    contactPerson: 'Sarah Mitchell',
    email: 'sarah.mitchell@dressagesa.com',
    phone: '+27 11 466 0346',
    address: '1 Allandale Road, Midrand',
    city: 'Johannesburg',
    province: 'Gauteng',
    postalCode: '1685',
    status: 'Active',
    dateCreated: new Date('2018-03-15'),
    isActive: true,
    website: 'https://www.kyalamiequestrianpark.co.za',
    description: 'Premier equestrian facility hosting national and international dressage competitions',
    facilities: ['Indoor Arena', 'Outdoor Arena', 'Stabling', 'Clubhouse', 'Parking'],
    instructorCount: 8,
    studentCapacity: 120,
    logo: 'assets/images/schools/kyalami.png'
  },
  {
    id: 2,
    name: 'Inanda Polo Club',
    type: 'Equestrian Club',
    contactPerson: 'Michael Thompson',
    email: 'michael.thompson@dressagesa.com',
    phone: '+27 11 465 1820',
    address: 'Inanda Road, Sandton',
    city: 'Johannesburg',
    province: 'Gauteng',
    postalCode: '2191',
    status: 'Active',
    dateCreated: new Date('2015-06-20'),
    isActive: true,
    website: 'https://www.inandapolo.co.za',
    description: 'Historic equestrian club offering dressage training and competitions',
    facilities: ['Polo Fields', 'Dressage Arena', 'Stabling', 'Restaurant'],
    instructorCount: 6,
    studentCapacity: 80,
    logo: 'assets/images/schools/inanda.png'
  },
  {
    id: 3,
    name: 'Summerveld Equestrian Centre',
    type: 'Training Center',
    contactPerson: 'Jennifer van der Merwe',
    email: 'jennifer.vandermerwe@dressagesa.com',
    phone: '+27 31 763 1234',
    address: 'Old Main Road, Summerveld',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    postalCode: '3610',
    status: 'Active',
    dateCreated: new Date('2019-01-10'),
    isActive: true,
    website: 'https://www.summerveldequestrian.co.za',
    description: 'Comprehensive training center specializing in dressage and show jumping',
    facilities: ['Indoor Arena', 'Outdoor Arena', 'Cross Country Course', 'Stabling'],
    instructorCount: 5,
    studentCapacity: 60,
    logo: 'assets/images/schools/summerveld.png'
  },
  {
    id: 4,
    name: 'Cape Dressage Academy',
    type: 'Riding School',
    contactPerson: 'Amanda Botha',
    email: 'amanda.botha@dressagesa.com',
    phone: '+27 21 855 3421',
    address: 'Stellenbosch Road, Somerset West',
    city: 'Cape Town',
    province: 'Western Cape',
    postalCode: '7130',
    status: 'Active',
    dateCreated: new Date('2017-09-05'),
    isActive: true,
    website: 'https://www.capedressage.co.za',
    description: 'Elite dressage training academy with international-level instructors',
    facilities: ['Indoor Arena', 'Outdoor Arena', 'Stabling', 'Tack Shop'],
    instructorCount: 7,
    studentCapacity: 90,
    logo: 'assets/images/schools/cape-dressage.png'
  },
  {
    id: 5,
    name: 'Riverside Riding School',
    type: 'Riding School',
    contactPerson: 'David Kruger',
    email: 'david.kruger@dressagesa.com',
    phone: '+27 12 809 1234',
    address: 'Riverside Road, Centurion',
    city: 'Pretoria',
    province: 'Gauteng',
    postalCode: '0157',
    status: 'Active',
    dateCreated: new Date('2016-04-12'),
    isActive: true,
    description: 'Family-friendly riding school offering lessons for all ages and levels',
    facilities: ['Outdoor Arena', 'Stabling', 'Paddocks'],
    instructorCount: 4,
    studentCapacity: 50
  },
  {
    id: 6,
    name: 'Stellenbosch Equestrian Centre',
    type: 'Training Center',
    contactPerson: 'Lisa Marais',
    email: 'lisa.marais@dressagesa.com',
    phone: '+27 21 887 5678',
    address: 'R44 Main Road, Stellenbosch',
    city: 'Stellenbosch',
    province: 'Western Cape',
    postalCode: '7600',
    status: 'Active',
    dateCreated: new Date('2014-11-20'),
    isActive: true,
    website: 'https://www.stellenboschequestrian.co.za',
    description: 'Premier training facility in the heart of the Winelands',
    facilities: ['Indoor Arena', 'Outdoor Arena', 'Stabling', 'Clubhouse', 'Viewing Gallery'],
    instructorCount: 6,
    studentCapacity: 75
  },
  {
    id: 7,
    name: 'Parkview Equestrian',
    type: 'Private Facility',
    contactPerson: 'Robert Wilson',
    email: 'robert.wilson@dressagesa.com',
    phone: '+27 11 447 8901',
    address: 'Jan Smuts Avenue, Parkview',
    city: 'Johannesburg',
    province: 'Gauteng',
    postalCode: '2193',
    status: 'Active',
    dateCreated: new Date('2020-02-14'),
    isActive: true,
    description: 'Boutique private facility for advanced dressage training',
    facilities: ['Outdoor Arena', 'Stabling', 'Paddocks'],
    instructorCount: 3,
    studentCapacity: 30
  },
  {
    id: 8,
    name: 'Bloemfontein Riding Academy',
    type: 'Riding School',
    contactPerson: 'Annelie Pretorius',
    email: 'annelie.pretorius@dressagesa.com',
    phone: '+27 51 436 7890',
    address: 'Naval Hill Road, Bloemfontein',
    city: 'Bloemfontein',
    province: 'Free State',
    postalCode: '9301',
    status: 'Active',
    dateCreated: new Date('2018-07-22'),
    isActive: true,
    description: 'Comprehensive riding academy serving the Free State region',
    facilities: ['Indoor Arena', 'Outdoor Arena', 'Stabling'],
    instructorCount: 5,
    studentCapacity: 65
  },
  {
    id: 9,
    name: 'Constantia Equestrian Estate',
    type: 'Equestrian Club',
    contactPerson: 'Catherine Smit',
    email: 'catherine.smit@dressagesa.com',
    phone: '+27 21 794 5432',
    address: 'Constantia Main Road, Constantia',
    city: 'Cape Town',
    province: 'Western Cape',
    postalCode: '7806',
    status: 'Active',
    dateCreated: new Date('2013-05-18'),
    isActive: true,
    website: 'https://www.constantiaequestrian.co.za',
    description: 'Exclusive equestrian estate with world-class facilities',
    facilities: ['Indoor Arena', 'Outdoor Arena', 'Stabling', 'Spa', 'Restaurant'],
    instructorCount: 9,
    studentCapacity: 100
  },
  {
    id: 10,
    name: 'Midlands Dressage Centre',
    type: 'Training Center',
    contactPerson: 'Peter Naidoo',
    email: 'peter.naidoo@dressagesa.com',
    phone: '+27 33 330 1234',
    address: 'Howick Road, Hilton',
    city: 'Pietermaritzburg',
    province: 'KwaZulu-Natal',
    postalCode: '3245',
    status: 'Inactive',
    dateCreated: new Date('2019-10-30'),
    isActive: false,
    description: 'Specialized dressage training center (temporarily closed for renovations)',
    facilities: ['Outdoor Arena', 'Stabling'],
    instructorCount: 2,
    studentCapacity: 40
  },
  {
    id: 11,
    name: 'Waterfall Equestrian Park',
    type: 'Competition Venue',
    contactPerson: 'Nicole van Zyl',
    email: 'nicole.vanzyl@dressagesa.com',
    phone: '+27 11 234 5678',
    address: 'Waterfall Drive, Waterfall',
    city: 'Johannesburg',
    province: 'Gauteng',
    postalCode: '2090',
    status: 'Active',
    dateCreated: new Date('2021-03-08'),
    isActive: true,
    website: 'https://www.waterfallequestrian.co.za',
    description: 'Modern equestrian park hosting regional and national competitions',
    facilities: ['Indoor Arena', 'Outdoor Arena', 'Stabling', 'Clubhouse', 'VIP Lounge'],
    instructorCount: 7,
    studentCapacity: 85
  },
  {
    id: 12,
    name: 'Port Elizabeth Riding School',
    type: 'Riding School',
    contactPerson: 'James Koopman',
    email: 'james.koopman@dressagesa.com',
    phone: '+27 41 367 8901',
    address: 'Marine Drive, Summerstrand',
    city: 'Port Elizabeth',
    province: 'Eastern Cape',
    postalCode: '6001',
    status: 'Active',
    dateCreated: new Date('2017-12-05'),
    isActive: true,
    description: 'Coastal riding school with scenic training facilities',
    facilities: ['Outdoor Arena', 'Beach Riding', 'Stabling'],
    instructorCount: 4,
    studentCapacity: 55
  },
  {
    id: 13,
    name: 'Nelspruit Equestrian Centre',
    type: 'Training Center',
    contactPerson: 'Thandi Mthembu',
    email: 'thandi.mthembu@dressagesa.com',
    phone: '+27 13 752 3456',
    address: 'White River Road, Nelspruit',
    city: 'Nelspruit',
    province: 'Mpumalanga',
    postalCode: '1200',
    status: 'Active',
    dateCreated: new Date('2020-08-17'),
    isActive: true,
    description: 'Growing equestrian center serving the Lowveld region',
    facilities: ['Outdoor Arena', 'Stabling', 'Paddocks'],
    instructorCount: 3,
    studentCapacity: 45
  },
  {
    id: 14,
    name: 'Hermanus Coastal Riding',
    type: 'Private Facility',
    contactPerson: 'Emma Fourie',
    email: 'emma.fourie@dressagesa.com',
    phone: '+27 28 312 4567',
    address: 'Hemel-en-Aarde Road, Hermanus',
    city: 'Hermanus',
    province: 'Western Cape',
    postalCode: '7200',
    status: 'Inactive',
    dateCreated: new Date('2016-09-25'),
    isActive: false,
    description: 'Private coastal facility (seasonal operations)',
    facilities: ['Outdoor Arena', 'Beach Access'],
    instructorCount: 2,
    studentCapacity: 25
  },
  {
    id: 15,
    name: 'Johannesburg Dressage Institute',
    type: 'Training Center',
    contactPerson: 'Dr. Heinrich Muller',
    email: 'heinrich.muller@dressagesa.com',
    phone: '+27 11 888 9012',
    address: 'Oxford Road, Rosebank',
    city: 'Johannesburg',
    province: 'Gauteng',
    postalCode: '2196',
    status: 'Active',
    dateCreated: new Date('2012-01-15'),
    isActive: true,
    website: 'https://www.jbgdressage.co.za',
    description: 'Leading dressage institute with FEI-certified instructors',
    facilities: ['Indoor Arena', 'Outdoor Arena', 'Stabling', 'Lecture Hall', 'Library'],
    instructorCount: 10,
    studentCapacity: 150
  }
];

