# Generated by Django 5.2 on 2026-04-02 03:48

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "saef_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="South African ID number (13 digits)",
                        max_length=13,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLACK_AFRICAN", "Black African"),
                            ("COLOURED", "Coloured"),
                            ("INDIAN", "Indian"),
                            ("WHITE", "White"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("nationality", django_countries.fields.CountryField(max_length=2)),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("suburb", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("CURRENT", "Current"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_test",
                    models.BooleanField(
                        default=False, help_text="Mark as test profile"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rider",
                "verbose_name_plural": "Riders",
                "db_table": "riders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rider Account",
                "verbose_name_plural": "Rider Accounts",
                "db_table": "rider_accounts",
                "ordering": ["-year__year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderClub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rider Club",
                "verbose_name_plural": "Rider Clubs",
                "db_table": "rider_clubs",
                "ordering": ["-year__year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderShowHoldingBody",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rider Show Holding Body",
                "verbose_name_plural": "Rider Show Holding Bodies",
                "db_table": "rider_show_holding_bodies",
                "ordering": ["-year__year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaefMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("membership_number", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SAEF Membership",
                "verbose_name_plural": "SAEF Memberships",
                "db_table": "saef_memberships",
                "ordering": ["-year__year", "-created_at"],
            },
        ),
    ]
