# Generated by Django 5.2 on 2026-04-02 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memberships", "0001_initial"),
        ("years", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "saef_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="South African ID number (13 digits)",
                        max_length=13,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLACK_AFRICAN", "Black African"),
                            ("COLOURED", "Coloured"),
                            ("INDIAN", "Indian"),
                            ("WHITE", "White"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("suburb", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("CURRENT", "Current"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_test",
                    models.BooleanField(
                        default=False, help_text="Mark as test profile"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider",
                "verbose_name_plural": "Riders",
                "db_table": "riders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="riders.rider",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rider_accounts",
                        to="memberships.subscription",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_accounts",
                        to="years.year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider Account",
                "verbose_name_plural": "Rider Accounts",
                "db_table": "rider_accounts",
                "ordering": ["-year__year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderClub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="riders.rider",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_clubs",
                        to="years.year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider Club",
                "verbose_name_plural": "Rider Clubs",
                "db_table": "rider_clubs",
                "ordering": ["-year__year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderShowHoldingBody",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_holding_bodies",
                        to="riders.rider",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_show_holding_bodies",
                        to="years.year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider Show Holding Body",
                "verbose_name_plural": "Rider Show Holding Bodies",
                "db_table": "rider_show_holding_bodies",
                "ordering": ["-year__year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaefMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("membership_number", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saef_memberships",
                        to="riders.rider",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saef_memberships",
                        to="years.year",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAEF Membership",
                "verbose_name_plural": "SAEF Memberships",
                "db_table": "saef_memberships",
                "ordering": ["-year__year", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(
                fields=["saef_number"], name="riders_saef_nu_696abf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(fields=["id_number"], name="riders_id_numb_ebdc58_idx"),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(
                fields=["passport_number"], name="riders_passpor_e3157d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(fields=["is_active"], name="riders_is_acti_c414a3_idx"),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(fields=["created_at"], name="riders_created_dbe7cb_idx"),
        ),
        migrations.AddIndex(
            model_name="rideraccount",
            index=models.Index(
                fields=["rider", "year"], name="rider_accou_rider_i_baa115_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rideraccount",
            index=models.Index(
                fields=["is_active"], name="rider_accou_is_acti_f5cd51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rideraccount",
            index=models.Index(
                fields=["created_at"], name="rider_accou_created_0c5772_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rideraccount",
            unique_together={("rider", "year")},
        ),
        migrations.AddIndex(
            model_name="riderclub",
            index=models.Index(
                fields=["rider", "year"], name="rider_clubs_rider_i_56ca58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riderclub",
            index=models.Index(fields=["name"], name="rider_clubs_name_abf2d3_idx"),
        ),
        migrations.AddIndex(
            model_name="riderclub",
            index=models.Index(
                fields=["is_active"], name="rider_clubs_is_acti_c30faa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riderclub",
            index=models.Index(
                fields=["created_at"], name="rider_clubs_created_827de6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="riderclub",
            unique_together={("rider", "year")},
        ),
        migrations.AddIndex(
            model_name="ridershowholdingbody",
            index=models.Index(
                fields=["rider", "year"], name="rider_show__rider_i_68499f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ridershowholdingbody",
            index=models.Index(fields=["name"], name="rider_show__name_3e5152_idx"),
        ),
        migrations.AddIndex(
            model_name="ridershowholdingbody",
            index=models.Index(
                fields=["is_active"], name="rider_show__is_acti_d314ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ridershowholdingbody",
            index=models.Index(
                fields=["created_at"], name="rider_show__created_7c2c16_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ridershowholdingbody",
            unique_together={("rider", "year")},
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["rider", "year"], name="saef_member_rider_i_ab6a1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["membership_number"], name="saef_member_members_e9651f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["is_active"], name="saef_member_is_acti_474cc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["expiry_date"], name="saef_member_expiry__51b1d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["created_at"], name="saef_member_created_9e38ee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saefmembership",
            unique_together={("rider", "year")},
        ),
    ]
