# Generated by Django 5.2 on 2026-04-02 02:40

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("riders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rider",
            name="nationality",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
