# Generated by Django 5.2 on 2026-04-02 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memberships", "0001_initial"),
        ("riders", "0001_initial"),
        ("years", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rideraccount",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="riders.rider",
            ),
        ),
        migrations.AddField(
            model_name="rideraccount",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rider_accounts",
                to="memberships.subscription",
            ),
        ),
        migrations.AddField(
            model_name="rideraccount",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider_accounts",
                to="years.year",
            ),
        ),
        migrations.AddField(
            model_name="riderclub",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubs",
                to="riders.rider",
            ),
        ),
        migrations.AddField(
            model_name="riderclub",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider_clubs",
                to="years.year",
            ),
        ),
        migrations.AddField(
            model_name="ridershowholdingbody",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="show_holding_bodies",
                to="riders.rider",
            ),
        ),
        migrations.AddField(
            model_name="ridershowholdingbody",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider_show_holding_bodies",
                to="years.year",
            ),
        ),
        migrations.AddField(
            model_name="saefmembership",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saef_memberships",
                to="riders.rider",
            ),
        ),
        migrations.AddField(
            model_name="saefmembership",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saef_memberships",
                to="years.year",
            ),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(
                fields=["saef_number"], name="riders_saef_nu_696abf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(fields=["id_number"], name="riders_id_numb_ebdc58_idx"),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(
                fields=["passport_number"], name="riders_passpor_e3157d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(fields=["is_active"], name="riders_is_acti_c414a3_idx"),
        ),
        migrations.AddIndex(
            model_name="rider",
            index=models.Index(fields=["created_at"], name="riders_created_dbe7cb_idx"),
        ),
        migrations.AddIndex(
            model_name="rideraccount",
            index=models.Index(
                fields=["rider", "year"], name="rider_accou_rider_i_baa115_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rideraccount",
            index=models.Index(
                fields=["is_active"], name="rider_accou_is_acti_f5cd51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rideraccount",
            index=models.Index(
                fields=["created_at"], name="rider_accou_created_0c5772_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rideraccount",
            unique_together={("rider", "year")},
        ),
        migrations.AddIndex(
            model_name="riderclub",
            index=models.Index(
                fields=["rider", "year"], name="rider_clubs_rider_i_56ca58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riderclub",
            index=models.Index(fields=["name"], name="rider_clubs_name_abf2d3_idx"),
        ),
        migrations.AddIndex(
            model_name="riderclub",
            index=models.Index(
                fields=["is_active"], name="rider_clubs_is_acti_c30faa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riderclub",
            index=models.Index(
                fields=["created_at"], name="rider_clubs_created_827de6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="riderclub",
            unique_together={("rider", "year")},
        ),
        migrations.AddIndex(
            model_name="ridershowholdingbody",
            index=models.Index(
                fields=["rider", "year"], name="rider_show__rider_i_68499f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ridershowholdingbody",
            index=models.Index(fields=["name"], name="rider_show__name_3e5152_idx"),
        ),
        migrations.AddIndex(
            model_name="ridershowholdingbody",
            index=models.Index(
                fields=["is_active"], name="rider_show__is_acti_d314ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ridershowholdingbody",
            index=models.Index(
                fields=["created_at"], name="rider_show__created_7c2c16_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ridershowholdingbody",
            unique_together={("rider", "year")},
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["rider", "year"], name="saef_member_rider_i_ab6a1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["membership_number"], name="saef_member_members_e9651f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["is_active"], name="saef_member_is_acti_474cc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["expiry_date"], name="saef_member_expiry__51b1d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saefmembership",
            index=models.Index(
                fields=["created_at"], name="saef_member_created_9e38ee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saefmembership",
            unique_together={("rider", "year")},
        ),
    ]
