/**
 * Colors Mock Data
 * Realistic sample data for horse colors/coat colors
 */

import { Color } from './colors-list-type';

export const COLORS: Color[] = [
  {
    id: 1,
    name: 'Bay',
    code: 'BAY',
    description: 'Brown body with black mane, tail, and lower legs',
    hexCode: '#8B4513',
    category: 'Base Color',
    isCommon: true,
    status: 'Active',
    isActive: true,
    displayOrder: 1,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-03-15'),
    notes: 'One of the most common horse colors'
  },
  {
    id: 2,
    name: 'Chestnut',
    code: 'CHEST',
    description: 'Reddish-brown body, mane, and tail',
    hexCode: '#CD853F',
    category: 'Base Color',
    isCommon: true,
    status: 'Active',
    isActive: true,
    displayOrder: 2,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-02-20')
  },
  {
    id: 3,
    name: 'Black',
    code: 'BLACK',
    description: 'Solid black coat, mane, and tail',
    hexCode: '#000000',
    category: 'Base Color',
    isCommon: true,
    status: 'Active',
    isActive: true,
    displayOrder: 3,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-03-01')
  },
  {
    id: 4,
    name: 'Grey',
    code: 'GREY',
    description: 'Grey coat that lightens with age, can range from dark to white',
    hexCode: '#808080',
    category: 'Base Color',
    isCommon: true,
    status: 'Active',
    isActive: true,
    displayOrder: 4,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-01-25')
  },
  {
    id: 5,
    name: 'Palomino',
    code: 'PAL',
    description: 'Golden coat with white or light mane and tail',
    hexCode: '#FFD700',
    category: 'Dilution',
    isCommon: false,
    status: 'Active',
    isActive: true,
    displayOrder: 5,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-02-14')
  },
  {
    id: 6,
    name: 'Dun',
    code: 'DUN',
    description: 'Tan or gold body with primitive markings and darker points',
    hexCode: '#D2B48C',
    category: 'Dilution',
    isCommon: false,
    status: 'Active',
    isActive: true,
    displayOrder: 6,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-03-10')
  },
  {
    id: 7,
    name: 'Buckskin',
    code: 'BUCK',
    description: 'Tan or gold body with black mane, tail, and lower legs',
    hexCode: '#D2B48C',
    category: 'Dilution',
    isCommon: false,
    status: 'Active',
    isActive: true,
    displayOrder: 7,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-02-05')
  },
  {
    id: 8,
    name: 'Roan',
    code: 'ROAN',
    description: 'Base color mixed with white hairs throughout the body',
    hexCode: '#BC8F8F',
    category: 'Pattern',
    isCommon: false,
    status: 'Active',
    isActive: true,
    displayOrder: 8,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-01-30')
  },
  {
    id: 9,
    name: 'Pinto',
    code: 'PINTO',
    description: 'Large patches of white and another color',
    hexCode: '#FFFFFF',
    category: 'Pattern',
    isCommon: false,
    status: 'Active',
    isActive: true,
    displayOrder: 9,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-03-05')
  },
  {
    id: 10,
    name: 'Appaloosa',
    code: 'APPY',
    description: 'Spotted coat pattern with various base colors',
    hexCode: '#FFFFFF',
    category: 'Pattern',
    isCommon: false,
    status: 'Active',
    isActive: true,
    displayOrder: 10,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-02-28')
  },
  {
    id: 11,
    name: 'Cremello',
    code: 'CREM',
    description: 'Cream-colored coat with blue eyes',
    hexCode: '#FFFACD',
    category: 'Dilution',
    isCommon: false,
    status: 'Active',
    isActive: true,
    displayOrder: 11,
    dateCreated: new Date('2023-02-15'),
    dateUpdated: new Date('2024-01-20')
  },
  {
    id: 12,
    name: 'Liver Chestnut',
    code: 'LIVER',
    description: 'Very dark reddish-brown, almost chocolate colored',
    hexCode: '#654321',
    category: 'Base Color',
    isCommon: false,
    status: 'Active',
    isActive: true,
    displayOrder: 12,
    dateCreated: new Date('2023-03-01'),
    dateUpdated: new Date('2024-02-10')
  },
  {
    id: 13,
    name: 'Sorrel',
    code: 'SORREL',
    description: 'Light reddish-brown, similar to chestnut',
    hexCode: '#D2691E',
    category: 'Base Color',
    isCommon: true,
    status: 'Active',
    isActive: true,
    displayOrder: 13,
    dateCreated: new Date('2023-03-15'),
    dateUpdated: new Date('2024-01-15')
  },
  {
    id: 14,
    name: 'Brown (Deprecated)',
    code: 'BROWN_OLD',
    description: 'Old classification - now categorized as dark bay',
    hexCode: '#654321',
    category: 'Base Color',
    isCommon: false,
    status: 'Inactive',
    isActive: false,
    displayOrder: 99,
    dateCreated: new Date('2022-06-01'),
    dateUpdated: new Date('2023-12-31'),
    notes: 'Deprecated - use Bay or Dark Bay instead'
  }
];

