/**
 * Judges List Mock Data
 * Realistic test data for the Judges List feature
 */

import { Judge } from './judges-list-type';

/**
 * Mock Judges Data
 * 15 realistic Judges with diverse types and statuses
 */
export const JUDGES: Judge[] = [
  {
    id: 1,
    firstName: 'Sarah',
    lastName: 'Mitchell',
    email: 'sarah.mitchell@dressage.co.za',
    phone: '+27 21 794 3000',
    judgeType: 'International',
    licenseNumber: 'FEI-JDG-2018-001',
    image: 'assets/images/judges/judge-1.jpg',
    status: 'Active',
    dateCreated: new Date('2018-03-15'),
    isActive: true,
    province: 'Western Cape',
    city: 'Cape Town',
    specialization: 'Grand Prix',
    yearsOfExperience: 15,
    certificationDate: new Date('2008-06-20')
  },
  {
    id: 2,
    firstName: 'Michael',
    lastName: 'Thompson',
    email: 'michael.thompson@dressage.com',
    phone: '+27 11 883 5000',
    judgeType: 'National',
    licenseNumber: 'SAEF-JDG-2019-015',
    image: 'assets/images/judges/judge-2.jpg',
    status: 'Active',
    dateCreated: new Date('2019-06-20'),
    isActive: true,
    province: 'Gauteng',
    city: 'Johannesburg',
    specialization: 'Intermediate',
    yearsOfExperience: 12,
    certificationDate: new Date('2011-09-15')
  },
  {
    id: 3,
    firstName: 'Jennifer',
    lastName: 'Adams',
    email: 'jennifer.adams@dressage.co.za',
    phone: '+27 31 561 4000',
    judgeType: 'International',
    licenseNumber: 'FEI-JDG-2017-008',
    image: 'assets/images/judges/judge-3.jpg',
    status: 'Active',
    dateCreated: new Date('2017-01-10'),
    isActive: true,
    province: 'KwaZulu-Natal',
    city: 'Durban',
    specialization: 'Grand Prix Special',
    yearsOfExperience: 18,
    certificationDate: new Date('2005-04-12')
  },
  {
    id: 4,
    firstName: 'David',
    lastName: 'Williams',
    email: 'david.williams@dressage.com',
    phone: '+27 12 346 8000',
    judgeType: 'National',
    licenseNumber: 'SAEF-JDG-2020-022',
    image: 'assets/images/judges/judge-4.jpg',
    status: 'Active',
    dateCreated: new Date('2020-09-05'),
    isActive: true,
    province: 'Gauteng',
    city: 'Pretoria',
    specialization: 'Elementary',
    yearsOfExperience: 8,
    certificationDate: new Date('2015-11-20')
  },
  {
    id: 5,
    firstName: 'Emma',
    lastName: 'van der Merwe',
    email: 'emma.vandermerwe@dressage.co.za',
    phone: '+27 21 887 2000',
    judgeType: 'Candidate',
    licenseNumber: 'SAEF-JDG-2022-012',
    image: 'assets/images/judges/judge-5.jpg',
    status: 'Inactive',
    dateCreated: new Date('2022-07-22'),
    isActive: false,
    province: 'Western Cape',
    city: 'Stellenbosch',
    specialization: 'Preliminary',
    yearsOfExperience: 3,
    certificationDate: new Date('2020-02-10')
  },
  {
    id: 6,
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.johnson@dressage.com',
    phone: '+27 41 583 3000',
    judgeType: 'National',
    licenseNumber: 'SAEF-JDG-2018-030',
    image: 'assets/images/judges/judge-1.jpg',
    status: 'Active',
    dateCreated: new Date('2018-11-18'),
    isActive: true,
    province: 'Eastern Cape',
    city: 'Gqeberha',
    specialization: 'Medium',
    yearsOfExperience: 10,
    certificationDate: new Date('2013-05-15')
  },
  {
    id: 7,
    firstName: 'Linda',
    lastName: 'Botha',
    email: 'linda.botha@dressage.co.za',
    phone: '+27 51 447 9000',
    judgeType: 'Apprentice',
    licenseNumber: 'SAEF-JDG-2023-005',
    image: 'assets/images/judges/judge-2.jpg',
    status: 'Active',
    dateCreated: new Date('2023-04-12'),
    isActive: true,
    province: 'Free State',
    city: 'Bloemfontein',
    specialization: 'Novice',
    yearsOfExperience: 2,
    certificationDate: new Date('2021-08-30')
  },
  {
    id: 8,
    firstName: 'James',
    lastName: 'Peterson',
    email: 'james.peterson@dressage.com',
    phone: '+27 33 345 7000',
    judgeType: 'National',
    licenseNumber: 'SAEF-JDG-2019-018',
    image: 'assets/images/judges/judge-3.jpg',
    status: 'Active',
    dateCreated: new Date('2019-10-08'),
    isActive: true,
    province: 'KwaZulu-Natal',
    city: 'Pietermaritzburg',
    specialization: 'Advanced',
    yearsOfExperience: 11,
    certificationDate: new Date('2012-03-25')
  },
  {
    id: 9,
    firstName: 'Sophie',
    lastName: 'Kruger',
    email: 'sophie.kruger@dressage.co.za',
    phone: '+27 13 752 5000',
    judgeType: 'International',
    licenseNumber: 'FEI-JDG-2016-003',
    image: 'assets/images/judges/judge-4.jpg',
    status: 'Active',
    dateCreated: new Date('2016-02-14'),
    isActive: true,
    province: 'Mpumalanga',
    city: 'Mbombela',
    specialization: 'Freestyle',
    yearsOfExperience: 20,
    certificationDate: new Date('2003-07-18')
  },
  {
    id: 10,
    firstName: 'Thomas',
    lastName: 'Maluleke',
    email: 'thomas.maluleke@dressage.com',
    phone: '+27 15 297 6000',
    judgeType: 'Candidate',
    licenseNumber: 'SAEF-JDG-2023-025',
    image: 'assets/images/judges/judge-5.jpg',
    status: 'Inactive',
    dateCreated: new Date('2023-08-30'),
    isActive: false,
    province: 'Limpopo',
    city: 'Polokwane',
    specialization: 'Preliminary',
    yearsOfExperience: 1,
    certificationDate: new Date('2022-10-05')
  },
  {
    id: 11,
    firstName: 'Patricia',
    lastName: 'Nkosi',
    email: 'patricia.nkosi@dressage.co.za',
    phone: '+27 53 831 7000',
    judgeType: 'National',
    licenseNumber: 'SAEF-JDG-2020-011',
    image: 'assets/images/judges/judge-1.jpg',
    status: 'Active',
    dateCreated: new Date('2020-06-25'),
    isActive: true,
    province: 'Northern Cape',
    city: 'Kimberley',
    specialization: 'Medium',
    yearsOfExperience: 7,
    certificationDate: new Date('2016-12-10')
  },
  {
    id: 12,
    firstName: 'Andrew',
    lastName: 'Smith',
    email: 'andrew.smith@dressage.com',
    phone: '+27 44 874 4000',
    judgeType: 'International',
    licenseNumber: 'FEI-JDG-2015-009',
    image: 'assets/images/judges/judge-2.jpg',
    status: 'Active',
    dateCreated: new Date('2015-05-17'),
    isActive: true,
    province: 'Western Cape',
    city: 'George',
    specialization: 'Grand Prix',
    yearsOfExperience: 22,
    certificationDate: new Date('2001-03-14')
  }
];

