/**
 * Breeds Mock Data
 * Realistic sample data for horse breeds commonly used in dressage
 */

import { Breed } from './breeds-list-type';

export const BREEDS: Breed[] = [
  {
    id: 1,
    name: 'Warmblood',
    code: 'WARM',
    description: 'Sport horses bred specifically for dressage, show jumping, and eventing',
    origin: 'Europe',
    characteristics: 'Athletic build, good temperament, excellent movement',
    averageHeight: '16-17 hands',
    temperament: 'Calm, willing, intelligent',
    status: 'Active',
    isActive: true,
    displayOrder: 1,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-03-15'),
    notes: 'Most popular breed for competitive dressage'
  },
  {
    id: 2,
    name: 'Hanoverian',
    code: 'HANN',
    description: 'German warmblood breed known for exceptional dressage ability',
    origin: 'Germany',
    characteristics: 'Powerful hindquarters, elegant movement, strong back',
    averageHeight: '15.3-17 hands',
    temperament: 'Willing, trainable, bold',
    status: 'Active',
    isActive: true,
    displayOrder: 2,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-02-20')
  },
  {
    id: 3,
    name: 'Dutch Warmblood (KWPN)',
    code: 'KWPN',
    description: 'Dutch sport horse with excellent dressage and jumping bloodlines',
    origin: 'Netherlands',
    characteristics: 'Powerful, athletic, excellent gaits',
    averageHeight: '16-17 hands',
    temperament: 'Energetic, willing, intelligent',
    status: 'Active',
    isActive: true,
    displayOrder: 3,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-03-01')
  },
  {
    id: 4,
    name: 'Oldenburg',
    code: 'OLD',
    description: 'German warmblood with strong dressage heritage',
    origin: 'Germany',
    characteristics: 'Strong, elegant, expressive movement',
    averageHeight: '16-17.2 hands',
    temperament: 'Calm, willing, trainable',
    status: 'Active',
    isActive: true,
    displayOrder: 4,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-01-25')
  },
  {
    id: 5,
    name: 'Andalusian',
    code: 'AND',
    description: 'Spanish breed known for classical dressage and high school movements',
    origin: 'Spain',
    characteristics: 'Compact, powerful, natural collection',
    averageHeight: '15.2-16.2 hands',
    temperament: 'Intelligent, sensitive, proud',
    status: 'Active',
    isActive: true,
    displayOrder: 5,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-02-14')
  },
  {
    id: 6,
    name: 'Friesian',
    code: 'FRIE',
    description: 'Dutch breed with dramatic movement and presence',
    origin: 'Netherlands',
    characteristics: 'Black coat, feathered legs, high knee action',
    averageHeight: '15-17 hands',
    temperament: 'Gentle, willing, people-oriented',
    status: 'Active',
    isActive: true,
    displayOrder: 6,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-03-10')
  },
  {
    id: 7,
    name: 'Thoroughbred',
    code: 'TB',
    description: 'Hot-blooded breed used in dressage for athleticism and sensitivity',
    origin: 'England',
    characteristics: 'Athletic, refined, spirited',
    averageHeight: '15.2-17 hands',
    temperament: 'Hot-blooded, sensitive, brave',
    status: 'Active',
    isActive: true,
    displayOrder: 7,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-02-05')
  },
  {
    id: 8,
    name: 'Lusitano',
    code: 'LUS',
    description: 'Portuguese breed similar to Andalusian, excellent for classical dressage',
    origin: 'Portugal',
    characteristics: 'Compact, powerful, agile',
    averageHeight: '15.1-16.2 hands',
    temperament: 'Intelligent, brave, willing',
    status: 'Active',
    isActive: true,
    displayOrder: 8,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-01-30')
  },
  {
    id: 9,
    name: 'Trakehner',
    code: 'TRAK',
    description: 'German warmblood with Thoroughbred influence, elegant and athletic',
    origin: 'Germany',
    characteristics: 'Refined, athletic, floating movement',
    averageHeight: '16-17 hands',
    temperament: 'Spirited, willing, intelligent',
    status: 'Active',
    isActive: true,
    displayOrder: 9,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-03-05')
  },
  {
    id: 10,
    name: 'Danish Warmblood',
    code: 'DWB',
    description: 'Danish sport horse with excellent dressage capabilities',
    origin: 'Denmark',
    characteristics: 'Athletic, powerful, good temperament',
    averageHeight: '16-17 hands',
    temperament: 'Calm, trainable, willing',
    status: 'Active',
    isActive: true,
    displayOrder: 10,
    dateCreated: new Date('2023-01-10'),
    dateUpdated: new Date('2024-02-28')
  },
  {
    id: 11,
    name: 'Lipizzaner',
    code: 'LIP',
    description: 'Classical dressage breed from the Spanish Riding School',
    origin: 'Austria',
    characteristics: 'Compact, powerful, natural aptitude for collection',
    averageHeight: '15-16.1 hands',
    temperament: 'Intelligent, willing, trainable',
    status: 'Active',
    isActive: true,
    displayOrder: 11,
    dateCreated: new Date('2023-02-15'),
    dateUpdated: new Date('2024-01-20')
  },
  {
    id: 12,
    name: 'Selle Français',
    code: 'SF',
    description: 'French sport horse with versatility in dressage and jumping',
    origin: 'France',
    characteristics: 'Athletic, powerful, good movement',
    averageHeight: '16-17 hands',
    temperament: 'Willing, brave, intelligent',
    status: 'Active',
    isActive: true,
    displayOrder: 12,
    dateCreated: new Date('2023-03-01'),
    dateUpdated: new Date('2024-02-10')
  },
  {
    id: 13,
    name: 'Quarter Horse (Deprecated)',
    code: 'QH_OLD',
    description: 'American breed - rarely used in classical dressage',
    origin: 'United States',
    characteristics: 'Compact, muscular, quick',
    averageHeight: '14.3-16 hands',
    temperament: 'Calm, willing, versatile',
    status: 'Inactive',
    isActive: false,
    displayOrder: 99,
    dateCreated: new Date('2022-06-01'),
    dateUpdated: new Date('2023-12-31'),
    notes: 'Deprecated - not commonly used for dressage competitions'
  }
];

